### ISSUE TITLE
Better retries around storage

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/chains#100]
If we're storing multiple payloads on multiple backends, we'll retry if any of the storage uploads failed. This means we may retry storing something that was successfully uploaded the first time, which some of our backends don't like.

We could either make all the operations safe to retry, or be more specific about what we retry.

**Comment by priyawadhwa** [comment]
I think docdb was the only backend that complained about this, but if there are others lmk & I can try to fix those as well!
