### ISSUE TITLE
Switch to using packageurl-go library for creating package URLs

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#108]
We generate package URLs for the intoto formatter:
https://github.com/tektoncd/chains/blob/39916b794dd2b4d9216d6bc01b9e27b507317dfa/pkg/chains/formats/intotoite6/intotoite6.go#L313

Instead of creating the string ourselves, it would be nice if we could use the library to do it for us: https://github.com/package-url/packageurl-go

I briefly tried to add it in myself, but the library returns a percent-encoded string, and I'm not totally sure if that's what we're supposed to be using (right now we aren't percent-encoding strings)

https://github.com/package-url/packageurl-go/blob/0789fa562603bb38a897134d735e7fc7ddf44b1e/packageurl.go#L83-L84

**Comment by dlorenc** [comment]
Honestly I kind of really don't like the purl spec for docker containers. It's ugly to use, it's ugly to special case them too.

cc @jonjohnsonjr tell me what to do here.

**Comment by jonjohnsonjr** [comment]
It seems like it would be better to just invent an entirely new thing. [This](https://github.com/package-url/packageurl-go/blob/0789fa562603bb38a897134d735e7fc7ddf44b1e/packageurl.go#L44-L74) just seems like the purl data model is a big [category mistake](https://en.wikipedia.org/wiki/Category_mistake), and I don't see how you could build something useful on top of that abstraction. How can golang, npm, and GitHub be in the same category? What kind of type system is this??

I might just not understand something, and I'd gladly be proven wrong.

**Comment by dlorenc** [comment]
> It seems like it would be better to just invent an entirely new thing. [This](https://github.com/package-url/packageurl-go/blob/0789fa562603bb38a897134d735e7fc7ddf44b1e/packageurl.go#L44-L74) appears to me like a [category mistake](https://en.wikipedia.org/wiki/Category_mistake), and I don't see how you could build something useful on top of that abstraction. How can golang, npm, and GitHub be in the same category? What kind of type system is this??
> 
> I might just not understand something, and I'd gladly be proven wrong.

That was my guess...

**Comment by priyawadhwa** [comment]
>Honestly I kind of really don't like the purl spec for docker containers. It's ugly to use, it's ugly to special case them too.

Yah I agree

Looks like the in-toto spec only _recommends_ the package url format ([details](https://github.com/in-toto/attestation/blob/main/spec/field_types.md#ResourceURI)) -- we could potentially just put in the image name (qualified with a digest) for OCI images instead?
