### ISSUE TITLE
Currently tektoncd/chains uses `Deprecated` in-toto/in-toto-golang `Subject`, `StatementHeader`, etc. structs. 

### ISSUE THREAD

**Issue by aaron-prindle** [tektoncd/chains#1087]
Currently tektoncd/chains uses deprecated https://github.com/in-toto/in-toto-golang structs:
 - intoto.Subject{...}
 - intoto.StatementHeader{...}
- intoto.ProvenanceStatementSLSA1{...}
- intoto.StatementInTotoV01{...}

https://github.com/in-toto/in-toto-golang/commit/32351740df5f3e9c079d4fe12bcf27271e2290b1

https://github.com/in-toto/in-toto-golang/blob/master/in_toto/attestations.go#L32-L42

We should update tektoncd/chains code to use the correct structs

Possibly related: https://github.com/tektoncd/chains/issues/920

**Comment by renzodavid9** [comment]
With the work we did in https://github.com/tektoncd/chains/pull/1111 and https://github.com/tektoncd/chains/pull/1118, we migrated the structs to the non-deprecated versions. I think it should be fine to close this issue @chitrangpatel

**Comment by chitrangpatel** [comment]
agreed!
