### ISSUE TITLE
Chains does not generate provenance for images built in a matrix

### ISSUE THREAD

**Issue by arewm** [tektoncd/chains#1164]
# Expected Behavior

Chains should sign and attest all container images referenced in results of matrixed TaskRuns

# Actual Behavior

All images are signed but there is only a provenance attestation for the first image.

# Steps to Reproduce the Problem

1. Create a pipeline that uses a matrix to build container images
2. Only the first will have an attestation

**Comment by lcarva** [comment]
The issue seems to be during the creation of the SLSA Provenance for PipelineRuns. If the underlying Pipeline uses [matrix](https://tekton.dev/docs/pipelines/matrix/), Chains only includes one instance of the corresponding TaskRun.

The issue appears to be in https://github.com/tektoncd/chains/blob/be7c1baad4d239dea30f9973226ffaf931e67a0b/pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go#L103-L107

Notice how there is an assumption that PipelineTaskRuns have unique name within a Pipeline.

This is not true when matrix is used.

**Comment by jkhelil** [comment]
I tried once using this example for matrix/multi-arch-build https://github.com/jkhelil/tekton-matrix/
and can see attestation for the different platforms
What's wrong with my reproducer ?
` 
k create ns matrix
k apply -n matrix -k ./tekton-matrix/

 k describe pr multi-arch-build-run -n matrix
Name:         multi-arch-build-run
Namespace:    matrix1
Labels:       tekton.dev/pipeline=multi-arch-build
Annotations:  chains.tekton.dev/signed: true
API Version:  tekton.dev/v1
Kind:         PipelineRun
Metadata:
  Creation Timestamp:  2024-07-29T12:45:36Z
  Finalizers:
    chains.tekton.dev/pipelinerun
  Generation:        1
  Resource Version:  131409
  UID:               2d6d3767-0475-40ac-92e3-26946b9673fb
Spec:
  Params:
    Name:   git-repo
    Value:  https://github.com/jkhelil/minimal-container
    Name:   git-revision
    Value:  main
    Name:   output-image
    Value:  quay.io/jkhelil/minimal-container-matrix1
    Name:   platforms
    Value:
      linux/amd64
      linux/arm64
      linux/arm/v7
  Pipeline Ref:
    Name:  multi-arch-build
  Task Run Template:
    Service Account Name:  default
  Timeouts:
    Pipeline:  1h0m0s
  Workspaces:
    Name:  shared
    Persistent Volume Claim:
      Claim Name:  tekton-build
Status:
  Child References:
    API Version:         tekton.dev/v1
    Kind:                TaskRun
    Name:                multi-arch-build-run-git-clone
    Pipeline Task Name:  git-clone
    API Version:         tekton.dev/v1
    Kind:                TaskRun
    Name:                multi-arch-build-run-build-images-1
    Pipeline Task Name:  build-images
    API Version:         tekton.dev/v1
    Kind:                TaskRun
    Name:                multi-arch-build-run-build-images-2
    Pipeline Task Name:  build-images
    API Version:         tekton.dev/v1
    Kind:                TaskRun
    Name:                multi-arch-build-run-build-images-0
    Pipeline Task Name:  build-images
  Completion Time:       2024-07-29T12:45:55Z
  Conditions:
    Last Transition Time:  2024-07-29T12:45:55Z
    Message:               Tasks Completed: 2 (Failed: 0, Cancelled 0), Skipped: 0
    Reason:                Succeeded
    Status:                True
    Type:                  Succeeded
  Pipeline Spec:
    Params:
      Description:  Repository URL to clone from.
      Name:         git-repo
      Type:         string
      Default:      main
      Description:  Revision to checkout. (branch, tag, sha, ref, etc...)
      Name:         git-revision
      Type:         string
      Description:  Reference of the image the pipeline will produce.
      Name:         output-image
      Type:         string
      Default:
        linux/amd64
        linux/arm64
      Description:  Target platforms for the image build.
      Name:         platforms
      Type:         array
    Tasks:
      Name:  git-clone
      Params:
        Name:   url
        Value:  https://github.com/jkhelil/minimal-container
        Name:   revision
        Value:  main
      Task Ref:
        Kind:  Task
        Name:  git-clone
      Workspaces:
        Name:       output
        Workspace:  shared
      Matrix:
        Params:
          Name:  PLATFORM
          Value:
            linux/amd64
            linux/arm64
            linux/arm/v7
      Name:  build-images
      Params:
        Name:   IMAGE
        Value:  quay.io/jkhelil/minimal-container-matrix1
        Name:   STORAGE_DRIVER
        Value:  vfs
      Run After:
        git-clone
      Task Ref:
        Kind:  Task
        Name:  buildah
      Workspaces:
        Name:       source
        Workspace:  shared
    Workspaces:
      Name:  shared
      
      
        tekton-matrix git:(main) skopeo inspect docker://quay.io/jkhelil/minimal-container-matrix1-linux/arm64 | jq '.RepoTags'
[
  "latest",
  "sha256-138a8b256f1003cb7e446aef3fdaaba3df3e10ce9880e59c9aabc5d6e3812fea.att",
  "sha256-138a8b256f1003cb7e446aef3fdaaba3df3e10ce9880e59c9aabc5d6e3812fea.sig"
]
➜  tekton-matrix git:(main) skopeo inspect docker://quay.io/jkhelil/minimal-container-matrix1-linux/amd64 | jq '.RepoTags'
[
  "latest",
  "sha256-504295beaf5053d77879e7e9f01f07cf8e475ea506878767d7bb090715944b3d.att",
  "sha256-504295beaf5053d77879e7e9f01f07cf8e475ea506878767d7bb090715944b3d.sig"
]
`

**Comment by arewm** [comment]
Even though Chains did not generate the pipeline provenance, the image _was_ signed. I assume that this is because Cosign recursively signed the Image Index that I produced as well.

**Comment by lcarva** [comment]
> Even though Chains did not generate the pipeline provenance, the image was signed. I assume that this is because Cosign recursively signed the Image Index that I produced as well.

Cosign can do this, but it is not the default behavior. Chains does not explicitly set this.

At the TaskRun level, Chains works properly because the TaskRun does emit the expected results. Since image signing happens at this level, that part works just fine.

The problem is with the PipelineRun attestation. Here, Chains is not properly handing the case where a PipelineRun contains multiple PipelineTaskRuns with the same name.

**Comment by jkhelil** [comment]
> @jkhelil, I suspect that the .sig and .att you are seeing are for the TaskRun-level artifacts. Can you verify that a PipelineRun attestation was generated for all the images?

yes thats correct, i can see the taskRun attestation only on the image
