### ISSUE TITLE
v0.3.0 Release

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#117]
Things we should definitely do:
- [x]  #100
- [x]  https://github.com/tektoncd/chains/issues/84
- [x] https://github.com/tektoncd/chains/issues/157
- [x] https://github.com/tektoncd/chains/pull/158
- [x] https://github.com/tektoncd/chains/pull/155

**Comment by dlorenc** [comment]
I think we're getting close here. WDYT @priyawadhwa ?
