### ISSUE TITLE
in-toto integration 

### ISSUE THREAD

**Issue by lukehinds** [tektoncd/chains#12]
Placeholder issue for in-toto integration tasks

@SantiagoTorres , hopefully you can see this.

- [x] Await on https://github.com/tektoncd/chains/pull/9 landing first
- [ ] Create simple python package, place onto test pypi
- [ ] Construct tasks and pipeline
- [ ] How will we query the link file?

Will need their own issues.
- [ ] Storage adapter
- [ ] Support more signing keys

**Comment by dlorenc** [comment]
OK, I'm going to get started on a skeleton PR for in-toto formatting next!

**Comment by dlorenc** [comment]
- [ ] Add some glue in chains to detect when a python package is built and sign/upload that to pip

**Comment by SantiagoTorres** [comment]
/reopen

I think this is still going on?
