### ISSUE TITLE
Chains configuration

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/chains#174]
We should consider making chains configurable so it can use a different set of criteria for making decisions based on some characteristics of the TaskRun.

A concrete example here is the Tekton CI set-up. We store everything right now in rekor, but we probably only care about release builds.

**Comment by dlorenc** [comment]
Cc @priyawadhwa

**Comment by priyawadhwa** [comment]
We could do it via annotations?

Create a new `manual` option for the chains config:

```yaml
transparency.enabled: manual
```

and then only add things to the log if this annotation is on the TaskRun:

```yaml
chains.tekton.dev/transparency: true
```

**Comment by dlorenc** [comment]
+1
