### ISSUE TITLE
Figure out how to store attestations on OCI images

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/chains#203]
We've started storing attestations for images in cosign using a ".att" suffix. We should figure out how to do that here in chains (right now we don't support storing attestations in OCI). I think the biggest challenge will be that the storage backends don't know what they're storing (signatures vs. attestations), and we hardcoded the ".sig" suffix.

cc @priyawadhwa any ideas?

**Comment by priyawadhwa** [comment]
I think we can check if the payload we're uploading is an OCI image or an in-toto statement, and if it's the image then create the signature the way we've been doing it with cosign

https://github.com/tektoncd/chains/blob/407e75f0b1ce57f7a7989247cb0a3ef435c04fe6/pkg/chains/storage/oci/oci.go#L89

and if it's the in-toto statement we can use the cosign library for generating the attestation layer & used the `cosign.AttestationTagSuffix` suffix and upload that

is there anything i'm missing?

**Comment by dlorenc** [comment]
nope, sgtm
