### ISSUE TITLE
Chains finalizer can block deletion indefinitely

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/chains#204]
# Expected Behavior

Deleting a namespace containing taskruns completes successfully.

# Actual Behavior

I am seeing the chains finalization failing because the service account gets cleaned up, which results in a reconciliation error, and the TaskRun sits around forever (keeping the namespace forever).

# Steps to Reproduce the Problem

I noticed this because I was running the pipelines e2e tests, which clean a lot of things up by deleting namespaces, and when I dug into why so much stuff was being left around, it looks a lot like this.

# Additional Info

Perhaps the finalization path should log, but not return errors? 🤷 

cc @priyawadhwa @dlorenc

**Comment by priyawadhwa** [comment]
> Perhaps the finalization path should log, but not return errors? 

That could work! 

I wonder if https://github.com/tektoncd/chains/pull/198 could resolve this as well -- right now Chains will continuously try to sign a TaskRun, and with this PR after 3 failures it'll mark the TaskRun as "failed" and move on.

**Comment by mattmoor** [comment]
Yeah that might work.
