### ISSUE TITLE
in-toto format includes repeat materials

### ISSUE THREAD

**Issue by 06kellyjac** [tektoncd/chains#239]
# Expected Behavior

Using the same image for multiple steps results in the same image appearing in the materials array multiple times

This could maybe be a concern if these get very long?

# Actual Behavior

Since the in-toto format lists an array of materials I don't see any benefit in listing out 3 times that an image was used if there's 3 steps using the same image.

If the digest.sha256 and or uri are identical there is no benefit to adding it to the materials list again.

I can understand it for the tekton format because it's more indepth as to the individual steps and such

# Steps to Reproduce the Problem

1. Run a task with multiple steps using the same image more than once
2. Check the in-toto materials array

**Comment by priyawadhwa** [comment]
Hey @06kellyjac thanks for opening an issue. Looking at the [spec](https://slsa.dev/provenance/v0.1), it doesn't really specify what to do in this case. I think it's probably fine to dedupe the list of materials.

Would you be interested in contributing a fix?

**Comment by 06kellyjac** [comment]
Sure :+1:
