### ISSUE TITLE
Check the image exists before uploading an attestation to OCI

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#246]
This seems like a reasonable check before we store attestations in registry

**Comment by loosebazooka** [comment]
Taking a look at this, is https://github.com/tektoncd/chains/blob/main/pkg/chains/storage/oci/oci.go#L166 not sufficient to verify an image does not exist?

**Comment by priyawadhwa** [comment]
good call! we can close this

**Comment by priyawadhwa** [comment]
opened https://github.com/tektoncd/chains/issues/296 as a related issue
