### ISSUE TITLE
Blog example is broken

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/chains#248]
# Expected Behavior

https://cd.foundation/blog/2021/06/18/verifiable-supply-chain-metadata-for-tekton/?utm_content=181854017 should work!

# Actual Behavior

It is broken, because I broke it 😞 

# Steps to Reproduce the Problem

Follow the blog

# Additional Info

I broke this here: https://github.com/tektoncd/chains/commit/00877044c7d97df600e0d8c5f7a2c14b1db12449#diff-9020fbd9f794f80f73f1ef60731819e812c1f92fb0448baba830ddb8a1fce808L52

I think with this change we could actually be able to simplify things by creating the single pull secret, mounting it into the task, and setting `DOCKER_CONFIG` instead of `GOOGLE_APPLICATION_DEFAULT`.

cc @priyawadhwa @dlorenc

**Comment by priyawadhwa** [comment]
> I think with this change we could actually be able to simplify things by creating the single pull secret, mounting it into the task, and setting DOCKER_CONFIG instead of GOOGLE_APPLICATION_DEFAULT.

I'm gonna give this a try, having one secret instead of two would definitely be better!

I've also asked if the blog post could be edited 🤞🏽  At the very least we could change
```
kubectl patch serviceaccount tekton-chains-controller \
  -p "{\"imagePullSecrets\": [{\"name\": \"registry-credentials\"}]}" -n tekton-chains
```
to 
```
kubectl patch serviceaccount default \
  -p "{\"imagePullSecrets\": [{\"name\": \"registry-credentials\"}]}" -n default
```
to apply the `imagePullSecret` to the service account the task runs under.  If I can get one secret to work I'll add that in instead.

**Comment by mattmoor** [comment]
Exactly.

But I think if we can switch things to `DOCKER_CONFIG` using pull secrets, the example will also become more portable, which I like.

**Comment by priyawadhwa** [comment]
For sure, here's a gist -- https://gist.github.com/priyawadhwa/f6f7365dcfbc63722c5999fb2a7e704f

I basically created the `registry-credentials` secret from the blog post. I can't seem to get a `dockerconfig` type secret to work with kaniko, so far I've only gotten a `generic` k8s secret generated from my docker `config.json` to work 😕

**Comment by priyawadhwa** [comment]
I ended up modifying the blog post with the simple fix above just so that it runs, but i still have to give your method a try @sbose78 !
