### ISSUE TITLE
Parse results to populate `materials` field in provenance

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#251]
Right now we look through params for [specific name/value combos](https://github.com/tektoncd/chains/blob/main/docs/intoto.md#standard-in-toto-predicate), but we should look at TaskRun results as well.

**Comment by sbose78** [comment]
Hi @priyawadhwa,

Do you imply that the following 
```
Status:
  # […]
  Steps:
  # […]
  Task Results:
    Name:   current-date-human-readable
    Value:  Thu Jan 23 16:29:06 UTC 2020

    Name:   current-date-unix-timestamp
    Value:  1579796946
```

.. should get populated in "materials" ? Sorry for the obvious question! If yes, I'd like to pick up this issue unless you already have it in WIP somewhere.
