### ISSUE TITLE
Adding hints to off-the-shelf tasks

### ISSUE THREAD

**Issue by sbose78** [tektoncd/chains#267]
Greetings!

Have we considered introducing other mechanisms of hinting (like annotations) to specify where to pick up the IMAGES/IMAGE_URL/IMAGE_DIGEST information from, in an off-the-shelf Task which isn't adhering to the naming conventions used for hinting today ?

**Comment by priyawadhwa** [comment]
Hey @sbose78 we haven't considered this yet. Is there a reason annotations would work better for you?
