### ISSUE TITLE
support for multiple output providers simultaneously

### ISSUE THREAD

**Issue by 06kellyjac** [tektoncd/chains#288]
### Feature request

support for multiple output providers simultaneously for cases where provenance needs to be stored in multiple places

### Use case

1. Migration
  * An organization might already have provenance storage set up for a provider e.g. `oci` and they want to move to document storage `docdb` and to ease the transition they might want to output to both simultaneously during that transition/migration period
2. Duplication due to requirements, regulated or otherwise
  * An organization's security policy or regulatory requirements may dictate the data needs to be stored within multiple systems be it for redundancy or different methods of analysis/usage
    * e.g. `docdb` for querying, `oci` for keeping the provenance next to signatures, or `gcs` for longer term archive storage
    * If there is an issue with one of the storage methods either due to chains or an outage with that particular method of storage

---

*Also:* There is also the potential to support 2+ output locations for the same provider type e.g. for 2 separate `gcs` buckets, sending a copy to a 3rd party security operations center
This might be outside the scope of this Feature Request so it could go in a separate ticket/issue

**Comment by priyawadhwa** [comment]
Hey @06kellyjac thank for opening this issue! I think this is a great idea.

Right now we have a config option where users choose the storage backend they want:
```
artifacts.taskrun.storage=[oci|gcs|docdb|tekton]
```

There are a couple ways we could add in multiple backends:
1. Turn the config value into a comma-separated list e.g. `artifacts.taskrun.storage=oci,gcs`

2. Separate each backend into its own config key:
```
artifacts.taskrun.storage.oci=enabled
artifacts.taskrun.storage.gcs=enabled
```
this could actually go hand in hand with https://github.com/tektoncd/chains/issues/279 (we could just assume that if no storage backend is enabled, then the entire artifact is disabled)

**Comment by 06kellyjac** [comment]
I like the 

```
artifacts.taskrun.storage.oci.enabled = true
artifacts.taskrun.storage.gcs.enabled = true
```

method since it keeps `enabled` alongside the other options like bucket name etc

For the `artifacts.taskrun.storage=oci,gcs` option it probably wouldn't be a comma separated list but a single string OR array

```
artifacts.taskrun.storage:
  - gcs
  - something
```

but again I think I prefer option 2 you proposed
