### ISSUE TITLE
Distinguish attestations during storage

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#296]
Right now when we upload to OCI we distinguish between signatures and attestations.

We could do the same when uploading to gcs, tekton and docdb and append the ".att" suffix to help distinguish. 

for gcs this change would happen here:
https://github.com/tektoncd/chains/blob/e5f8d4424255798a633e200420fc00d8c19c044b/pkg/chains/storage/gcs/gcs.go#L66

and etc for the other backends

**Comment by loosebazooka** [comment]
I'll take a look

**Comment by loosebazooka** [comment]
Just to check my understanding.

Attestations will exist only for payloads that are of payload type "`in-toto`/`tekoton-provenance`", other types should just follow the existing flow and write raw payloads to the storage backend?

```
if payloadtype = "in-toto" or "tekton-provenance" {
  call it an attestation?
}
else {
  call it a payload?
}
```

**Comment by priyawadhwa** [comment]
so basically payloads are always either a "signature" or an "attestation" (also signed). this check basically is used to determine which one is which.  We can probs copy cosign and append ".sig" for signatures and ".att" for attestations to help distinguish between the two!

**Comment by loosebazooka** [comment]
impl for gcs: https://github.com/tektoncd/chains/pull/300

**Comment by loosebazooka** [comment]
I'm a little confused about how this would look for the tekton backend? The tekton backend is storing stuff in the taskrun? Would it be cyclically referring to itself?

**Comment by priyawadhwa** [comment]
yup, it would pretty much either be storing the taskrun or the intoto attestation back on the taskrun itself

we could just change the annotation name here to indicate which payload it is, but tbh i don't think it's a big deal either way

**Comment by loosebazooka** [comment]
I think I'm missing something here, but what's the point of storing the taskrun in the taskrun? Is it storing a snapshot of the taskrun at a different time?

**Comment by priyawadhwa** [comment]
sort of, it's mostly just a convenient. it's a snapshot of the taskrun before chains modifies it. afterwards, chains adds the TaskRun (payload), signature, and any certs that may have been issued back onto the TaskRun as an annotation

users would have to strip those new annotations to get the original payload for signature verification (totally possible, just kinda annoying).

**Comment by loosebazooka** [comment]
gotcha, okay this makes sense now

**Comment by loosebazooka** [comment]
So after discussion, it seems like we want a way to store multiple signed data in the backends from different signing events.

Each new payload added to the backend must have an accompanying signature -- the pair/tuple should be a single unit that is referenceable in some way. If a signature is overwritten, the payload should not be left hanging (as would be the case with #300 -- so this will be reverted).

for multiple (payload, signature) coming from a single task run we need a datastructure that is a list of signing events
```
[]signingEvent {payload,signature,chain,cert}
```
where `backend.RetrieveSignature` and `backend.RetreivePayload` need to be reworked to handle the possibility of multiple signingEvents being store on the backend.
