### ISSUE TITLE
`IMAGES` should support newline delimiters

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/chains#311]
### Feature request

This code expects a `,` delimiter, but it would be great if this code would also support newlines: https://github.com/tektoncd/chains/blob/0c28d26827584af16f5d0bd43302a974ea5d2858/pkg/artifacts/signable.go#L159

### Use case

I feel like this makes producing and consuming this result simpler because to produce you could use append: `>> /tekton/results/IMAGES` and to consume (in other contexts) you can use: `cosign sign $(cat /tekton/results/IMAGES)`

cc @dlorenc @priyawadhwa

**Comment by dlorenc** [comment]
+1

**Comment by mattmoor** [comment]
I went with newline in https://github.com/google/ko/pull/555 so with that and this folks could use:
```
ko resolve --image-refs=/tekton/results/IMAGES -BRf config > /tekton/results/YAMLZ
```

**Comment by dlorenc** [comment]
We have an issue to support this as an input to cosign already right?

**Comment by mattmoor** [comment]
Yeah.  Newline allows `$(cat /tekton/results/IMAGES)` already, but I think `cosign` should support reading this from a file so we don't always need a shell.
