### ISSUE TITLE
Update Chains authentication doc with auth for DockerHub

### ISSUE THREAD

**Issue by concaf** [tektoncd/chains#314]
# Expected Behavior
Chains is able to sign images on Docker Hub.

# Actual Behavior
Chains is unable to sign images on Docker Hub while it works fine on GCR.

# Steps to Reproduce the Problem

I followed the [signed provenance tutorial](https://github.com/tektoncd/chains/blob/main/docs/tutorials/signed-provenance-tutorial.md) so these steps are from there:

1.  Install Tekton Chains
1. Set up authentication for the registry (namespace `default`) -
    ```
    kubectl create secret docker-registry registry-credentials --docker-server=docker.io --docker-username=$DOCKERHUB_USERNAME --docker-email=$DOCKERHUB_EMAIL --docker-password=$DOCKERHUB_PASSWORD`
    kubectl patch serviceaccount default  -p "{\"imagePullSecrets\": [{\"name\": \"registry-credentials\"}]}" -n default
    ```
1. Generate a key pair
    ```
    cosign generate-key-pair k8s://tekton-chains/signing-secrets
    ```
1. Configure authentication for the kaniko task:
    ```
    docker login (log in to Docker Hub)
    kubectl create secret generic secret-docker-hub --from-file ~/.docker/config.json
    ```
1. Configure Tekton Chains
    ```
    kubectl patch configmap chains-config -n tekton-chains -p='{"data":{"artifacts.taskrun.format": "in-toto"}}'
    kubectl patch configmap chains-config -n tekton-chains -p='{"data":{"artifacts.taskrun.storage": "oci"}}'
    kubectl patch configmap chains-config -n tekton-chains -p='{"data":{"transparency.enabled": "true"}}'
    ```
1. Apply and start the `kaniko` task
    ```
    kubectl apply -f https://raw.githubusercontent.com/tektoncd/chains/main/examples/kaniko/kaniko.yaml
    tkn task start --param IMAGE=docker.io/<Docker Hub registry name>/kaniko-chains --use-param-defaults --workspace name=source,emptyDir="" --workspace name=dockerconfig,secret=secret-docker-hub kaniko-chains
    ```
1. Wait for the TaskRun to finish and for it to report that signing has failed
    ```
    kubectl get tr [TASKRUN_NAME] -o json | jq -r .metadata.annotations
    ```
    Look for, `"chains.tekton.dev/signed": "failed"` in the annotations

# Additional Info

- Here is a relevant error from the `tekton-chains-controller` pod:
`
{"level":"error","ts":"2022-01-01T13:39:18.427Z","logger":"watcher","caller":"chains/signing.go:210","msg":"POST https://index.docker.io/v2/concaf/kaniko-chains/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:concaf/kaniko-chains Type:repository] map[Action:push Class: Name:concaf/kaniko-chains Type:repository]]","commit":"0c28d26","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"8b965ddc-4fd9-44db-9763-6ade25dd06c1","knative.dev/key":"default/kaniko-chains-run-k6wlb","stacktrace":"github.com/tektoncd/chains/pkg/chains.(*TaskRunSigner).SignTaskRun\n\tgithub.com/tektoncd/chains/pkg/chains/signing.go:210\ngithub.com/tektoncd/chains/pkg/reconciler/taskrun.(*Reconciler).FinalizeKind\n\tgithub.com/tektoncd/chains/pkg/reconciler/taskrun/taskrun.go:61\ngithub.com/tektoncd/chains/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/chains/pkg/reconciler/taskrun/taskrun.go:42\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline@v0.27.1-0.20210830150214-8afd1563782d/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:249\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20211123135150-787aec59e70a/controller/controller.go:542\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20211123135150-787aec59e70a/controller/controller.go:478"}
`
- I think the code that is failing is here - https://github.com/tektoncd/chains/blob/243e90b3736f2fa4daa013c38c1cefba254cf106/pkg/chains/storage/oci/oci.go#L188-L191
but I was not able to dig deeper since I don't understand it fully.
- I suspect this might be related to https://github.com/sigstore/cosign/issues/587
- Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

- Tekton Pipeline version:
```
$ tkn version
Client version: dev
Pipeline version: v0.31.0
```

- Docker version - `20.10.12`

**Comment by priyawadhwa** [comment]
Hey @concaf thanks for opening this issue. It does seem really related to the cosign issue you linked. Just to make sure the `config.json` has the expected info, could you include what's in it with the sensitive information removed?

**Comment by concaf** [comment]
@priyawadhwa sure, this is how my `~/.docker/config.json` looks like -
```json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "redacted"
                }
        }
}
```
I even tried different variations of this per this comment - https://github.com/sigstore/cosign/issues/587#issuecomment-1003072134
```json
{
        "auths": {
                "docker.io": {
                        "auth": "redacted"
                },
                "https://index.docker.io/v1/": {
                        "auth": "redacted"
                },
                "https://index.docker.io/v2/": {
                        "auth": "redacted"
                }
        }
}
```
but no luck.

**Comment by priyawadhwa** [comment]
Thanks @concaf for sharing that. I was able to get this to work by following the k8s docs [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials) 
 to create the dockerconfig secret. It seems like the way suggested in the tutorial doesn't work for DockerHub! 

When I used the originally suggested way, the base64 encoded secret actually looked like this:

```
$ kubectl create secret docker-registry registry-credentials-docker --docker-server=docker.io --docker-username=$DOCKERHUB_USERNAME --docker-email=$DOCKERHUB_EMAIL --docker-password=$DOCKERHUB_PASSWORD`

$ kubectl get secret registry-credentials-docker -o json | jq -r '.data.".dockerconfigjson"' | base64 --decode | jq
{
  "auths": {
    "docker.io": {
      "username": "priyawadhwa",
      "password": [redacted],
      "email":  [redacted],
      "auth":  [redacted]
    }
  }
}
```

which isn't the expected format. 


Creating the secret as suggested in the docs resulted in the expected `config.json` format:

```
$ kubectl create secret generic regcred \
    --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
    --type=kubernetes.io/dockerconfigjson

$ kubectl patch serviceaccount default  -p "{\"imagePullSecrets\": [{\"name\": \"regcred\"}]}" -n default

$ kubectl get secret regcred -o json | jq -r '.data.".dockerconfigjson"' | base64 --decode | jq
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "redacted"
    }
}
```

and I was able to verify the signature was uploaded with cosign! Let me know if that works for you, and if so then we can update the docs :)

**Comment by sbose78** [comment]
Just looked up my stored secret, this is what I used to use, along with patching the relevant `sa`.

```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "redacted"
                }
        }
}
```

**Comment by sbose78** [comment]
This doesn't seem to be working for me anymore :( 
Went a version back, that works!

https://github.com/tektoncd/chains/issues/320

**Comment by priyawadhwa** [comment]
hey @sbose78 , if you try to create the secret the way I described in https://github.com/tektoncd/chains/issues/314#issuecomment-1005752385, does it still fail for you?

**Comment by sbose78** [comment]
@priyawadhwa , yeah I did that without any success. I'm guessing there's a permission issue 🤔

**Comment by concaf** [comment]
@priyawadhwa just got some time to try this out and 🎉 yay 🎉, it worked per your comment https://github.com/tektoncd/chains/issues/314#issuecomment-1005752385, thank you! Will send a PR for the fix.

The docs that need to be updated are here, right? - https://github.com/tektoncd/chains/blob/main/docs/authentication.md

**Comment by concaf** [comment]
@sbose78 judging my the logs, #320 seems a bit different 🤔

**Comment by priyawadhwa** [comment]
Hey @concaf glad it's working! Yup, let's update the docs to in this [section](https://github.com/tektoncd/chains/blob/main/docs/authentication.md#authenticating-to-an-oci-registry) to include creating the secret for dockerhub :)

**Comment by priyawadhwa** [comment]
@sbose78 we can try and resolve the bug you opened in #320 since it seems unrelated!

**Comment by concaf** [comment]
/remove-lifecycle stale
working on this today
