### ISSUE TITLE
Replace `"google"` auth with cosign's ambient credential logic.

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/chains#317]
### Feature request

I'd propose changing the default `FulcioAuth` strategy from `"google"` to `"auto"` (or possibly removing it entirely) and replacing the existing `fulcioSigner` logic here: https://github.com/tektoncd/chains/blob/eee44752460aa08dcba1f520af088c8134e45c2f/pkg/chains/signing/x509/x509.go#L62-L92

With a call to [`github.com/sigstore/cosign/pkg/providers.Provide`](https://github.com/sigstore/cosign/blob/1a7f9d61a2e9199ba27b4910435784c56a21ff1a/pkg/providers/interface.go#L64)

### Use case

This makes the story for configuring how `chains` authenticates align with how you'd authenticate a `cosign` call within a Task step (e.g. mounting a projected volume token at a specific path).  This would immediately allow Chains to support keyless signing from EKS clusters and with SPIFFE.  It would also enable Chains on KinD to sign against a Fulcio running locally on the KinD cluster!

**Comment by mattmoor** [comment]
cc @priyawadhwa @vaikas 

I noticed this as I was preparing: https://github.com/tektoncd/chains/pull/316.  I'd forgotten this only supported Google auth, and the oidc-magic stuff should be a pretty trivial way of expanding the support here.

**Comment by priyawadhwa** [comment]
This is a great idea! I think removing the FulcioAuth strategy would be the best move alongside this.

**Comment by vaikas** [comment]
Getting consistency with the auth story would surely be fantastic!

**Comment by mattmoor** [comment]
Awesome, I'll see if one of our recruits wants to pick this up, but comment here if you are looking into it so we don't duplicate efforts!

**Comment by priyawadhwa** [comment]
I started taking a look, just working on getting the integration test to pass now :)

**Comment by mattmoor** [comment]
Awesome :party-priya:
