### ISSUE TITLE
Error uploading signature and attestation

### ISSUE THREAD

**Issue by sbose78** [tektoncd/chains#320]
I upgraded from v0.5.0 today and I'm getting a `getting signed image: open containers/auth.json: permission denied` in the logs. This seems to be happening while the "Starting attestation upload to OCI " is attempted. Seems to me that the signature isn't getting pushed to OCI for the same reason. 

* Major changes post v0.5.x include https://github.com/tektoncd/chains/pull/284
* The error message appeared in https://github.com/tektoncd/chains/pull/291/commits/07c1b5ffb72c5474c86dbbdccbcb49aa7a7f98b5

# Expected Behavior

Upload of signature & attestation with tekton-provenance should succeed in chains v0.6.x, since it had worked in 0.5.x ( I'm aware tekton-provenance has been deprecated, that shouldn't impact this 🤔  )

# Actual Behavior

Signing fails.

```
{"level":"info","ts":"2022-01-10T00:23:58.771Z","logger":"watcher","caller":"chains/signing.go:185","msg":"Signing object with x509","commit":"48a85c4","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"fb99b1f9-acdf-434a-87eb-1787388908c5","knative.dev/key":"tekton-chains/new-pipeline-sye5yl-buildah-2gms7"}
{"level":"info","ts":"2022-01-10T00:23:58.771Z","logger":"watcher","caller":"oci/oci.go:71","msg":"Storing payload on TaskRun tekton-chains/new-pipeline-sye5yl-buildah-2gms7","commit":"48a85c4","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"fb99b1f9-acdf-434a-87eb-1787388908c5","knative.dev/key":"tekton-chains/new-pipeline-sye5yl-buildah-2gms7"}
{"level":"info","ts":"2022-01-10T00:23:58.771Z","logger":"watcher","caller":"oci/oci.go:147","msg":"Starting to upload attestations to OCI ...","commit":"48a85c4","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"fb99b1f9-acdf-434a-87eb-1787388908c5","knative.dev/key":"tekton-chains/new-pipeline-sye5yl-buildah-2gms7"}
{"level":"info","ts":"2022-01-10T00:23:58.771Z","logger":"watcher","caller":"oci/oci.go:150","msg":"Starting attestation upload to OCI for index.docker.io/sbose78/foobar@sha256:ca76bc767e181c4a2a03413fe84bd7608a969a2fdd9646b0c262dc82149ec06f...","commit":"48a85c4","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"fb99b1f9-acdf-434a-87eb-1787388908c5","knative.dev/key":"tekton-chains/new-pipeline-sye5yl-buildah-2gms7"}
{"level":"error","ts":"2022-01-10T00:23:58.772Z","logger":"watcher","caller":"chains/signing.go:207","msg":"getting signed image: open containers/auth.json: permission denied","commit":"48a85c4","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"fb99b1f9-acdf-434a-87eb-1787388908c5","knative.dev/key":"tekton-chains/new-pipeline-sye5yl-buildah-2gms7","stacktrace":"github.com/tektoncd/chains/pkg/chains.(*TaskRunSigner).SignTaskRun\n\tgithub.com/tektoncd/chains/pkg/chains/signing.go:207\ngithub.com/tektoncd/chains/pkg/reconciler/taskrun.(*Reconciler).FinalizeKind\n\tgithub.com/tektoncd/chains/pkg/reconciler/taskrun/taskrun.go:61\ngithub.com/tektoncd/chains/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/chains/pkg/reconciler/taskrun/taskrun.go:42\ngithub.com/tektoncd/chains/vendor/github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Re...
{"level":"info","ts":"2022-01-10T00:23:59.126Z","logger":"watcher","caller":"chains/signing.go:217","msg":"Uploaded entry to https://rekor.sigstore.dev with index 1042420","commit":"48a85c4","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"fb99b1f9-acdf-434a-87eb-1787388908c5","knative.dev/key":"tekton-chains/new-pipeline-sye5yl-buildah-2gms7"}
{"level":"error","ts":"2022-01-10T00:23:59.145Z","logger":"watcher","caller":"taskrun/reconciler.go:308","msg":"Returned an error","commit":"48a85c4","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"fb99b1f9-acdf-434a-87eb-1787388908c5","knative.dev/key":"tekton-chains/new-pipeline-sye5yl-buildah-2gms7","targetMethod":"ReconcileKind","error":"1 error occurred:\n\t* getting signed image: open containers/auth.json: permission denied\n\n","stacktrace":"github.com/tektoncd/chains/vendor/github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/chains/vendor/github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:308\ngithub.com/tektoncd/chains/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tgithub.com/tektoncd/chains/vendor/knative.dev/pkg/controller/controller.go:542\ngit...
{"level":"error","ts":"2022-01-10T00:23:59.145Z","logger":"watcher","caller":"controller/controller.go:566","msg":"Reconcile error","commit":"48a85c4","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"fb99b1f9-acdf-434a-87eb-1787388908c5","knative.dev/key":"tekton-chains/new-pipeline-sye5yl-buildah-2gms7","duration":1.368152566,"error":"1 error occurred:\n\t* getting signed image: open containers/auth.json: permission denied\n\n","stacktrace":"github.com/tektoncd/chains/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\tgithub.com/tektoncd/chains/vendor/knative.dev/pkg/controller/controller.go:566\ngithub.com/tektoncd/chains/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tgithub.com/tektoncd/chains/vendor/knative.dev/pkg/controller/controller.go:543\ngithub.com/tektoncd/chains/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3\n\tgithub.com/tektoncd/chains/vendor/knative.dev/pkg...
{"l
```

# Steps to Reproduce the Problem

With the following config,
```
  artifacts.taskrun.format: tekton-provenance
  artifacts.taskrun.storage: oci
  transparency.enabled: 'true'
```
0. Install chains v0.5.0 and create a Task/TaskRun for https://gist.github.com/sbose78/1e348752bd2de0e528d953f896f89d13 , ensure signature upload succeeds. This includes setting up of auth as per the docs https://github.com/tektoncd/chains/blob/main/docs/authentication.md
1. Upgrade from chains 0.5.0 to 0.6.1
2. Re-run the Task that had worked before.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+e790d7f", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2021-12-14T02:10:38Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:
v0.28.2

I'm pushing to Dockerhub.

**Comment by concaf** [comment]
@sbose78 surprisingly, I saw something like this some time back on OpenShift and `oc adm policy add-scc-to-user anyuid -n tekton-chains -z tekton-chains-controller` fixed it for me. Not sure if this helps though 😅

**Comment by priyawadhwa** [comment]
Hey @sbose78 so I tried to repro this @ HEAD with our [kaniko task](https://github.com/tektoncd/chains/blob/main/examples/kaniko/kaniko.yaml) and pushing to DockerHub. It worked as expected for me, so I looked into the error.

We use the [go-containerregistry](https://github.com/google/go-containerregistry) library for registry auth in k8s and based on their [auth doc](https://github.com/google/go-containerregistry/blob/a5c1d034e0df07e54b3971ac2eb34325725e4da3/pkg/authn/README.md#tldr-for-consumers-of-this-package):

> The DefaultKeychain will use credentials as described in your Docker config file -- usually ~/.docker/config.json, or %USERPROFILE%\.docker\config.json on Windows -- or the location described by the DOCKER_CONFIG environment variable, if set.

> If those are not found, DefaultKeychain will look for credentials configured using Podman's expectation that these are found in ${XDG_RUNTIME_DIR}/containers/auth.json.

Seems like the Chains controller isn't finding any Docker auth. How are you passing it in?

**Comment by sbose78** [comment]
@priyawadhwa I've been associating the `Secret` to the service account that's running the TaskRun. 

> @sbose78 surprisingly, I saw something like this some time back on OpenShift and oc adm policy add-scc-to-user anyuid -n tekton-chains -z tekton-chains-controller fixed it for me. Not sure if this helps though 😅

😮 I think that will work, let me try. I think that's what I had done a while ago as well.

**Comment by priyawadhwa** [comment]
@sbose78 cool, let us know if that fixes it!

**Comment by vdemeester** [comment]
> @sbose78 cool, let us know if that fixes it!

That fixes it but that shouldn't be necessary though. I think if there is no `$XDG_RUNTIME_DIR` set in the image, and thus it makes it look at `/containers/auth.json`, which.. is probably why the failure. I wonder why is this returned as an error though, in those case we should probably consider "not found" and "no permission" similarily, we couldn't get auth, let's move on. @imjasonh wdyt ?

**Comment by vdemeester** [comment]
https://github.com/google/go-containerregistry/blob/c6366444aa46d4d05854960485646f5d7a2bcd09/pkg/authn/keychain.go#L103 would probably need a better handling, using the `XDG_RUNTIME_DIR` default instead of nothing if the env is not there.

```
$XDG_RUNTIME_DIR defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored. The directory MUST be owned by the user, and he MUST be the only one having read and write access to it. Its Unix access mode MUST be 0700.
```
From https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html.

We should either set it in the chains controller image or update go-containerregistry that would default it to something that is 99% of the case user readable (by anybody).

**Comment by priyawadhwa** [comment]
I think between #342 and #346 this should be fixed?

**Comment by concaf** [comment]
Well, #342 should fix this particular error, I tried and it's working fine but I'd defer to @sbose78 for closing this.

Note: on OpenShift, due to #346 `anyuid` scc is still going to be required.

**Comment by imjasonh** [comment]
I think this is done. @sbose78 feel free to reopen if it's still not working.

/close
