### ISSUE TITLE
Event log (e.g. Kafka) attestation storage support

### ISSUE THREAD

**Issue by mlieberman85** [tektoncd/chains#356]
### Feature request

Ability to send attestations into an event log/stream system like Kafka. 

### Use case

Writing support for every backend that an enterprise might need isn't scalable compared to the increasingly common pattern of pushing to an event log like Kafka. This allows for organizations to utilize their own connectors for the event log rather than creating backend support for something that might only be relevant to the particular organization. It also greatly simplifies various workflows that might include metadata and attestations coming from Chains.

**Comment by priyawadhwa** [comment]
thanks for opening this @mlieberman85! lmk if anyone should be assigned to the issue.

**Comment by rgreinho** [comment]
This was solved by #386.

**Comment by mlieberman85** [comment]
> This was solved by #386.

Thanks! Closing issue
