### ISSUE TITLE
Add Grafeas as a storage backend

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#358]
### Feature request

To use Grafeas as a storage backend in Tekton Chains

### Background
Users can configure Tekton Chains based on their needs. Two main configurations are `artifacts.taskrun.format` and `artifacts.taskrun.storage`. By configuring `artifacts.taskrun.storage`, users can determine where to store the provenance and signature for the TaskRuns once they are created. Currently the options we have in Tekton Chains are within Tekton itself, an OCI registry, Google Cloud Storage (GCS) and docdb.

### Design
Now, we’re planning on adding [Grafeas](https://grafeas.io/) to Tekton Chains as a storage backend. Grafeas is an open artifact metadata API. It offers a central, structured knowledge-base of the artifact metadata that is critical to manage software supply chains.
We’ll follow up with more details. Comments and feedback are welcome!

**Comment by chuangw6** [comment]
#389

**Comment by priyawadhwa** [comment]
Hey @chuangw6 , can this be closed or is there more work to be done?

**Comment by chuangw6** [comment]
> Hey @chuangw6 , can this be closed or is there more work to be done?

Hi @priyawadhwa ,
There is more work to be done. Specifically, we want to change grafeas api from v1beta1 to v1.
