### ISSUE TITLE
Chains does not work on GCP if Metadata Services are disabled

### ISSUE THREAD

**Issue by lcarva** [tektoncd/chains#408]
# Expected Behavior
On a cluster deployed on GCP, the Tekton Chains controller should work properly and sign artifacts as per configuration.

# Actual Behavior
On a cluster deployed on GCP, the Tekton Chains controller halts execution if the cluster is running on GCP and [Metadata Services](https://cloud.google.com/compute/docs/metadata/overview) are not enabled.

# Steps to Reproduce the Problem

1. Grab a hold of cluster on GCP
2. Do not enable Metadata Services
3. Create a TaskRun, make sure it finishes successfully

Notice how the controller does not produce any sort of log messages to indicate it's processing the finalized TaskRun.

# Additional Info

- Kubernetes version:

```
🐚 kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-07-22T00:00:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+1f952b3", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-03-27T05:21:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.23) exceeds the supported minor version skew of +/-1
```

- Tekton Pipeline version:

```
🐚 tkn version
Client version: 0.21.0
Pipeline version: v0.28.3
Triggers version: v0.16.1
```

- OpenShift version:

```
 🐚 oc version
Client Version: 4.8.0-202201210133.p0.g88e7eba.assembly.stream-88e7eba
Server Version: 4.10.0-0.nightly-2022-03-29-163038
Kubernetes Version: v1.23.5+1f952b3
```

**Comment by lcarva** [comment]
The root cause of this issue appears to be an outdated version of the `google/go-containerregistry` library. See [details](https://github.com/vdemeester/k8s-pkg-credentialprovider/issues/18#issuecomment-1084249349).

Updating `google/go-containerregistry` should fix the issue. I have not been successful in doing this update.

**Comment by priyawadhwa** [comment]
hey @lcarva thanks for opening this bug. https://github.com/tektoncd/chains/pull/404/files includes an upgrade to go-containerregistry which should include the commit you pointed out

**Comment by lcarva** [comment]
I can verify that using those changes the issue reported here goes away. Thanks!
