### ISSUE TITLE
1.17 is now required to build the controller

### ISSUE THREAD

**Issue by lcarva** [tektoncd/chains#410]
# Expected Behavior

Compiling the controller should complete successfully with go 1.6 because that's what's specified in the go.mod file.

# Actual Behavior

```
🐚 go version
go version go1.16.15 linux/amd64

🐚 go build -mod=vendor ./cmd/controller
vendor/github.com/hashicorp/vault/sdk/helper/pluginutil/run_config.go:13:2: //go:build comment without // +build comment
```

# Steps to Reproduce the Problem

1. `go build -mod=vendor ./cmd/controller`

# Additional Info

Running `go build` with version `1.17.8` completes successfully.

**Comment by lcarva** [comment]
I think the changes from https://github.com/tektoncd/chains/pull/404 introduced this. Maybe we just need to update the version listed in `go.mod` ?

cc @priyawadhwa

**Comment by priyawadhwa** [comment]
Good catch, yup I think updating to 1.17 in go.mod should work!
