### ISSUE TITLE
Grafeas unit tests are flaky

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#426]
The grafeas `[pkg/chains/storage/grafeas TestBackend_ListOccurrences]` unit test is flaky:

```
    grafeas_test.go:85: Wrong list of occurrences received for empty filter, got=  (*grafeas_go_proto.ListOccurrencesResponse)(Inverse(protocmp.Transform, protocmp.Message{
          }))
```

an [example failure log](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_chains/420/pull-tekton-chains-unit-tests/1517164418503282689/) provided.

cc @chuangw6 who added this in, do you have any ideas why it might be flaky?

**Comment by chuangw6** [comment]
Hi @priyawadhwa ,
Thanks for reporting this. Just digged into this and found out it's because when retrieving all occurrences stored as a map in the fake server, the order retrieved sometimes is not same as the insertion order (as Go maps do not maintain the insertion order). So I added the code to sort all occurrences by resource uri when calling `ListOccurrences`. This will make sure the test is not flaky anymore.

**Comment by savitaashture** [comment]
Hi @chuangw6 and @priyawadhwa 
even we see chains nightly failing here https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns/chains-release-nightly-5wt2l?pipelineTask=unit-tests&step=unit-test
because of flakiness

**Comment by priyawadhwa** [comment]
Thank you @chuangw6 for looking into it! @savitaashture hopefully tonight's build passes now that the fix is about to be merged 🤞🏽

**Comment by chuangw6** [comment]
Yeah, now it should fix the issue. From the log, I see it failed because of the same issue I just mentioned. @savitaashture

**Comment by dprotaso** [comment]
This consistently fails here: https://github.com/knative/pkg/runs/6265134542?check_suite_focus=true

All that check is doing is testing the latest `knative.dev/pkg` with the latest chains version

```
--- FAIL: TestInitializeBackends (0.01s)
    logger.go:130: 2022-05-02T22:24:40.280Z	DEBUG	storage/storage_test.go:81	Backend: map[]
    logger.go:130: 2022-05-02T22:24:40.280Z	DEBUG	storage/storage_test.go:81	Backend: map[tekton:0xc000710348]
    --- FAIL: TestInitializeBackends/gcs (0.01s)
        storage_test.go:78: InitializeBackends() error = dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
    logger.go:130: 2022-05-02T22:24:40.287Z	DEBUG	storage/storage_test.go:81	Backend: map[oci:0xc000631a40]
    --- FAIL: TestInitializeBackends/grafeas (0.00s)
        storage_test.go:78: InitializeBackends() error = google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
    --- FAIL: TestInitializeBackends/multi (0.00s)
        storage_test.go:78: InitializeBackends() error = dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
    logger.go:130: 2022-05-02T22:24:40.288Z	DEBUG	storage/storage_test.go:81	Backend: map[pubsub:0xc00016ed00]
FAIL
FAIL	github.com/tektoncd/chains/pkg/chains/storage	0.174s
```

**Comment by chuangw6** [comment]
> This consistently fails here: https://github.com/knative/pkg/runs/6265134542?check_suite_focus=true
> 
> All that check is doing is testing the latest `knative.dev/pkg` with the latest chains version
> 
> ```
> --- FAIL: TestInitializeBackends (0.01s)
>     logger.go:130: 2022-05-02T22:24:40.280Z	DEBUG	storage/storage_test.go:81	Backend: map[]
>     logger.go:130: 2022-05-02T22:24:40.280Z	DEBUG	storage/storage_test.go:81	Backend: map[tekton:0xc000710348]
>     --- FAIL: TestInitializeBackends/gcs (0.01s)
>         storage_test.go:78: InitializeBackends() error = dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
>     logger.go:130: 2022-05-02T22:24:40.287Z	DEBUG	storage/storage_test.go:81	Backend: map[oci:0xc000631a40]
>     --- FAIL: TestInitializeBackends/grafeas (0.00s)
>         storage_test.go:78: InitializeBackends() error = google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
>     --- FAIL: TestInitializeBackends/multi (0.00s)
>         storage_test.go:78: InitializeBackends() error = dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
>     logger.go:130: 2022-05-02T22:24:40.288Z	DEBUG	storage/storage_test.go:81	Backend: map[pubsub:0xc00016ed00]
> FAIL
> FAIL	github.com/tektoncd/chains/pkg/chains/storage	0.174s
> ```

From looking at the logs, it seems not related to tests of `ListOccurrences` , and not even related to grafeas support because `TestInitializeBackends/gcs` test also throws error. 

I guess it might be because your github actions don't set any google application default credentials. And the tests failed, which indicated by the message like
```
    --- FAIL: TestInitializeBackends/gcs (0.01s)
        storage_test.go:78: InitializeBackends() error = dialing: **google: could not find default credentials.** See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by dprotaso** [comment]
weird - email reply didn't go through

> I guess it might be because your github actions don't set any google application default credentials

That makes sense - but why would a unit test require this?

**Comment by chuangw6** [comment]
> weird - email reply didn't go through
> 
> > I guess it might be because your github actions don't set any google application default credentials
> 
> That makes sense - but why would a unit test require this?

Hey @dprotaso ,
sorry for the delay. Just saw @imjasonh disabled the unit tests (for gcs backend storage creation) that require setting up credentials in #438.

I also disabled the unit tests for grafeas backend storage creation in #446. Hope these two prs will get rid of issues caused by missing credential setup.
Thanks.

**Comment by dprotaso** [comment]
These are unit tests - so I’m surprised by that expectation

**Comment by dprotaso** [comment]
That's weird - I didn't post that unless I did it in my sleep.

Maybe it was a draft
