### ISSUE TITLE
KeyID in Grafeas Occurrence

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#471]
### Feature request

When we create Grafeas occurrences, we only set the KMS key path `gcpkms://projects/<project>/locations/<location>/keyRings/<keyring>/cryptoKeys/<key>` as the keyID field of [the DSSE envelope](https://github.com/grafeas/grafeas/blob/0ec8596e37d3d853ef0ab8318f69b112cdc161ee/proto/v1/common.proto#L119).

If chains is configured to sign with k8s secret `signing-secrets` in the `tekton-chains` namespace, the key id field will be empty. 

In order to support this case, we might want to use the hard-coded `k8s://tekton-chains/signing-secrets` as the keyid for k8s secret signing since chains [expects](https://github.com/tektoncd/chains/blob/main/docs/signing.md#signing-secrets) signing keys to exist in a Kubernetes secret `signing-secrets` in the `tekton-chains` namespace..

### Use case
- Chains uses k8s secret to sign instead of KMS keys.

**Comment by chuangw6** [comment]
Thoughts? @wlynch @priyawadhwa

**Comment by wlynch** [comment]
Sorry for missing this! This seems fine.

Alternatively we could look into doing is including a fingerprint of the key, which will probably be more reliable in uniquely identifying a key since the value of the secret can change over time.
