### ISSUE TITLE
SLSA version in Tekton Chains

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#477]
Currently Tekton Chains generates intoto statement with [SLSA 0.2 predicate](https://slsa.dev/provenance/v0.2). However, we might expect breaking changes from SLSA version v0.X to v1.0 according to [the official doc](https://slsa.dev/provenance/v0.2) since it is constantly evolving ([SLSA roadmap](https://github.com/slsa-framework/slsa-proposals/blob/main/0002/README.md)).

> Note about 0.x versions
We expect regular iteration on 0.x versions until 1.0. During 0.x, we lean towards smaller, faster releases in order to get earlier feedback on the design. After 1.0, we will limit the frequency of breaking changes.
> To make this manageable, we recommend that:
> - Provenance generators choose the latest 0.x version at the time of implementation and then stick with that until 1.0 unless there is reason to upgrade before then.
> - Provenance consumers accept all known versions and convert internally between them.

This issue is to track supporting SLSA v1 provenance in Chains. 

If you have any questions, comments or concerns on the SLSA version changes in Chains, feel free to add them here.

**Comment by chuangw6** [comment]
## Concern
While supporting the latest SLSA provenance, we should avoid breaking the users/consumers who are still relying on the older SLSA version. 

## Proposal
1. Chains generates one intoto statement per SLSA version (that is, each intoto statement contains a specific version of SLSA predicate). 
2. To support 1/, Chains needs to use the [generic `Statement` struct](https://github.com/in-toto/in-toto-golang/blob/b4a6b184fd3ad4658e5018bc58e5f5a89fb23da5/in_toto/model.go#L980-L984) rather than the SLSA0.2-specific [`ProvenanceStatement `](https://github.com/in-toto/in-toto-golang/blob/b4a6b184fd3ad4658e5018bc58e5f5a89fb23da5/in_toto/model.go#L980-L984) struct from the [in-toto-golang](https://github.com/in-toto/in-toto-golang) package.

**Comment by wlynch** [comment]
Chatted with @chuangw6 about this a bit last week - I think we landed on a similar idea to yours @priyawadhwa! The alternative we were thinking of was allowing multiple values in the existing `artifacts.*.format` field, i.e. `intoto-v0.2`, `intoto-v1`, with the existing `intoto` value just being an alias to the latest version. Thinking about it more now, I think your approach might be better to add in a backwards compatible way (I'm not sure if we can move from string -> list without client config changes).

The other wrinkle to this is wanting to support multiple versions for phased rollouts. I agree we should avoid supporting all versions forever, but supporting a configured set seems reasonable for cases like upgrades. i.e. when we want to add SLSA v1, allow Chains to optionally write v0.2 and v1 (choose to pin to 1 version, or allow writing both), then turn down v0.2 once we consider v1 to be stable. wdyt?

**Comment by chuangw6** [comment]
Just want to clarify:

If we introduce the new `formats.in-toto.version` field, is it just an auxiliary field for the existing `artifacts.taskrun.format` field? 
To put it differently, users still need to configure the `in-toto` option for the `artifacts.taskrun.format` field. And when we see `in-toto` is selected, we check `formats.in-toto.version`: 
    - If `formats.in-toto.version` is empty or `intoto-v1`, we only generate the latest version. 
    - If `formats.in-toto.version` is a list i.e. `intoto-v0.2,intoto-v1`, we will generate multiple versions.

Is that the idea? @priyawadhwa @wlynch
