### ISSUE TITLE
Discuss whether Chains should check artifact's digest in TaskRun

### ISSUE THREAD

**Issue by ywluogg** [tektoncd/chains#485]
Per [the discussion thread](https://github.com/tektoncd/chains/pull/465#discussion_r916160951), it worths more discussions if Chains should check the existence of the artifact.
Here are a few things we are looking:
1. if digest matches the uri
2. if the uri exists

One idea is to not let Chains does this job, but rather, relying on [trusted tasks / resources](https://github.com/tektoncd/community/pull/739) to have a step to verify the above stuff, and trusted task can guarantee the task is not modified and the artifact is produced as expected. SPIRE, on the other hand, garantees the TaskRun hasn't been modified after the execution.

The other idea is that Chains can check one or more of the items listed above

**Comment by ywluogg** [comment]
@wlynch @priyawadhwa

**Comment by priyawadhwa** [comment]
From the [slsa doc](https://slsa.dev/spec/v0.1/requirements#identifies-artifact) it seems like this isn't required for level 2:

> The provenance MUST identify the output artifact via at least one cryptographic hash. The provenance MAY provide multiple identifying cryptographic hashes using different algorithms. When only one hash is provided, the RECOMMENDED algorithm is SHA-256 for cross-system compatibility. If another algorithm is used, it SHOULD be resistant to collisions and second preimages.
