### ISSUE TITLE
Upgrade to pipeline v1beta1 types

### ISSUE THREAD

**Issue by wlynch** [tektoncd/chains#522]
A bunch of v1alpha1 types have been removed in [Pipelines 0.38](https://github.com/tektoncd/pipeline/releases/tag/v0.38.0). This is blocking upgrade of the Pipelines dep - https://github.com/tektoncd/chains/pull/516

We should move our dependency to v1beta1.

**Comment by wlynch** [comment]
@ywluogg Interested in picking this up? 👀

**Comment by ywluogg** [comment]
> @ywluogg Interested in picking this up? 👀

Yes!
