### ISSUE TITLE
Document release processes for Chains

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/chains#535]
Document what the release process looks like:

- the release manager role
- how version numbers are used and their meaning
- the release frequency 
- the steps to perform a major and a minor release

Include the links to existing / new documents in the issue.

**Comment by Yongxuanzhang** [comment]
Existing doc is here https://github.com/tektoncd/chains/tree/main/release

**Comment by afrittoli** [comment]
> Existing doc is here https://github.com/tektoncd/chains/tree/main/release

Thank you @Yongxuanzhang - that looks good for "the steps to perform a major and a minor release". 
This is an example of the document from the pipeline repo: https://github.com/tektoncd/pipeline/blob/main/releases.md
