### ISSUE TITLE
Provide TaskRun annotations in SLSA provenance

### ISSUE THREAD

**Issue by zregvart** [tektoncd/chains#591]
### Feature request

I'm mostly interested in having the `experimental.tekton.dev/execution-mode` annotation available in the SLSA provenance. It might be useful to place all TaskRun annotations in there as well. A good place might be `invocation.environment.context`, similar to how this is done for GitHub Workflows in the [this example](https://slsa.dev/provenance/v0.2#github-actions).

### Use case

I want to see from the SLSA provenance if a build was done in hermetic environment or not. This allows me to evaluate the built result with higher level of confidence that there wasn't outside tampering with certain TaskRun. For example, for the build, having fetched the source code and having all the dependencies vendored I don't want to allow any external traffic, and I'd like to attest to that in the SLSA provenance generated for that TaskRun.

This was already proposed in #278, though it was closed as stale.

**Comment by wlynch** [comment]
SGTM!

I think `invocation.environment` makes sense, though perhaps it should be `invocation.environment.annotations`? 
I think context for GHA is specifically referring to https://docs.github.com/en/actions/learn-github-actions/contexts

**Comment by zregvart** [comment]
Might be also worth including the labels, but that could be done in a different issue.

**Comment by lcarva** [comment]
I have another use case where I need information from one of the PipelineRun labels to make a policy decision. Any objections in using `invocation.environment.annotations` for TaskRun/PipelineRun annotations and `invocation.environment.labels` for TaskRun/PipelineRun annotations?

Related question, for PipelineRuns, should we also include the labels and annotations of each TaskRun under `.buildConfig.task[].invocation` ?
