### ISSUE TITLE
TEP 109: implementation

### ISSUE THREAD

**Issue by ywluogg** [tektoncd/chains#592]
### Feature request

The issue tracks the implementation of [TEP 109](https://github.com/tektoncd/community/blob/main/teps/0109-better-structured-provenance-retrieval-in-tekton-chains.md) and log all followup items here

### Use case

- [x] Implementation: #491 
- [x] Update docs

### Future Work
- Run integration with structured values (#595)

**Comment by wlynch** [comment]
@ywluogg Can you update this issue with a [task list](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists) so it's easier to see what's left to do? 🙏

**Comment by ywluogg** [comment]
> @ywluogg Can you update this issue with a [task list](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists) so it's easier to see what's left to do? 🙏 (simple list is fine)

done!
