### ISSUE TITLE
PipelineRunObject adding supported to structured results

### ISSUE THREAD

**Issue by ywluogg** [tektoncd/chains#595]
### Feature request

Adding support of structured results in PipelineRunObject:
Currently TaskRunObject already have the structured results [being supported](https://github.com/tektoncd/chains/blob/780521656ab0ea2a72d7a969a13040848ac6b969/pkg/chains/objects/objects.go#L98-L99) but not PipelineRunObject. It seems straightforward to add those, just curious if there's anything concerning for adding those? @bcaton85 @lcarva fyi.

### Use case

Use Objects for structured results in PipelineRunObjects

**Comment by bcaton85** [comment]
I think this is a good idea. Given I don't have complete knowledge of structured results. Shouldn't be too difficult as long as the calls to `GetResults` for `PipelineRunObject` and `TaskRunObject` are still being interpreted correctly depending on the type. IIRC there is places where the pipelinerun results is expected to be string.

**Comment by ywluogg** [comment]
#599
