### ISSUE TITLE
Query: Use of Secrets Store CSI driver provider

### ISSUE THREAD

**Issue by mtcolman** [tektoncd/chains#609]
Hello,

Is it possible to use a Secrets Store CSI driver provider (for example for HashiCorp Vault) to inject the private key for signing, rather than storing it as a Kubernetes secret (as is stated [here](https://github.com/tektoncd/chains/blob/main/docs/signing.md#signing-secrets)):

>To get started signing things in Chains, you will need to generate a keypair and instruct Chains to sign with it via a Kubernetes secret. Chains expects a private key, and password if the key is encrypted, to exist in a Kubernetes secret signing-secrets in the tekton-chains namespace.

I'm keen to avoid storing any secrets we don't have to as Kubernetes Secrets and so we would like to use Vault + injection into pods where possible.

Thanks!

Matt

**Comment by lcarva** [comment]
Related to https://github.com/tektoncd/chains/pull/604 ?

**Comment by mtcolman** [comment]
@lcarva from what I can decipher on #604, I believe this is different.

**Comment by wlynch** [comment]
I don't think we support this today, though it wouldn't be too hard to add (we'd just need to add support for reading a key from a file). Main reason we haven't done this is that configuration would require modifying the deployment spec directly + redeployment of the controller, we we suspect most users don't want to do.

For vault in particular, you may want to look into https://github.com/tektoncd/chains/blob/main/docs/signing.md#kms

**Comment by mtcolman** [comment]
Thanks for your response. Are you please aware of any tutorials. step-by-step guides for using Hashicorp Vault with tekton-chains?

**Comment by cooktheryan** [comment]
@mtcolman did you have any luck with the configuration

**Comment by mtcolman** [comment]
@cooktheryan I didn't get round to trying it - I can't find any guidance on how to configure it.

**Comment by cooktheryan** [comment]
@mtcolman ill keep trying to hack on it. I also opened a documentation RFE
