### ISSUE TITLE
V1 Release Chains Support

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/chains#625]
### Feature request

V1 CRDs are released in https://github.com/tektoncd/pipeline/pull/5579 and this issue tracks down the according requests for the v1 support in chains.

**Comment by vdemeester** [comment]
This is actually a duplicate of https://github.com/tektoncd/chains/issues/665, I wonder which one to keep 🙃

**Comment by JeromeJu** [comment]
Let's keep #665 thanks @vdemeester 😇
