### ISSUE TITLE
The default builderID needs to be changed.

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#640]
# Background
One important field in SLSA provenance is [predicate.builder.builderID](https://slsa.dev/provenance/v0.2#builder). 

Chains does support setting this value via the configmap field named [builder.id](https://github.com/tektoncd/chains/blob/main/docs/config.md#in-toto-configuration), which is great and we'd like to keep this. But the default builderID `https://tekton.dev/chains/v2` set [here](https://github.com/tektoncd/chains/blob/6d80daed68aa9b08670b6213df02f763d077d31d/pkg/config/config.go#L240-L242) sounds not right.

# Expected Behavior
 
Chains has correct default value for the builder id.

# Actual Behavior

The default value used by Chains is `https://tekton.dev/chains/v2`. It doesn't make sense because Chains apparently is not the builder and doesn't contribute to the artifact build.

**Comment by wlynch** [comment]
We may want to derive this value from the run status itself so the controller can self-report - either by `app.kubernetes.io/managed-by`, [ManagedFieldsEntry](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#ManagedFieldsEntry) or some other mechanism.

**Comment by lcarva** [comment]
Builder is defined as:

> Identifies the entity that executed the invocation, which is trusted to have correctly performed the operation and populated this provenance.

I'm wondering if Tekton Chains is the correct value for builder. Isn't the builder actually Tekton Pipelines? It seems to fit the definition more accurately. The only exception being "populated this provenance", but, arguably, Tekton Pipelines does play an important role here as well.

**Comment by chuangw6** [comment]
> I'm wondering if Tekton Chains is the correct value for builder. Isn't the builder actually Tekton Pipelines? It seems to fit the definition more accurately. The only exception being "populated this provenance", but, arguably, **Tekton Pipelines does play an important role here as well.**

Yeah, that's a good call. I feel like thinking of Chains as a plugin/helper of Tekton Pipeline to assist in populating the provenance might help reconcile ourselves XD hahah. 

+1 to @wlynch 's idea.
We might want to handle this builderID in a similar way as component versions. The goal is to avoid information/version drift by making info available as part of installing Tekton and letting chains just pick up from CRD itself instead of configmap.

**Comment by lcarva** [comment]
/lifecycle frozen

There's some interest in resolving this relatively soon.

**Comment by lcarva** [comment]
@wlynch mentioned in slack today that keeping the ability to set the builder ID via config could be misused as a spoofing technique.

We should clarify that before working on this issue.

A spoofing attack would mean a certain Chains deployment can identify itself as a another Chains deployment. In order to do that successfully, the Chains deployment would also have to use the same signing key (or cert issuer/subject in keyless). If that happens, the builder ID is the least of your problems.

We should also keep in mind the upcoming [v1.0 SLSA Provenance spec](https://slsa.dev/provenance/v1#builder) which has some very specific requirements for this attribute:
> URI indicating the transitive closure of the trusted build platform. This is [intended](https://slsa.dev/spec/v1.0/verifying-artifacts#step-1-check-slsa-build-level) to be the sole determiner of the SLSA Build level.
>
> If a build platform has multiple modes of operations that have differing security attributes or SLSA Build levels, each mode MUST have a different builder.id and SHOULD have a different signer identity. This is to minimize the risk that a less secure mode compromises a more secure one.
>
> The builder.id URI SHOULD resolve to documentation explaining:
> 
>   * The scope of what this ID represents.
>   * The claimed SLSA Build level.
>   * The accuracy and completeness guarantees of the fields in the provenance.
>   * Any fields that are generated by the tenant-controlled build process and not verified by the trusted control plane, except for the subject.
>   * The interpretation of any extension fields.

**Comment by chitrangpatel** [comment]
Follow up in Issue https://github.com/tektoncd/pipeline/issues/6593

**Comment by chitrangpatel** [comment]
Marking this as done since https://github.com/tektoncd/pipeline/issues/6593 made it configurable
