### ISSUE TITLE
`predicate.materials` needs to record more information.

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#642]
# Expected Behavior

`predicate.materials` should record all the artifacts that influence the build according to [slsa definition](https://slsa.dev/provenance/v0.2#materials)

> The collection of artifacts that influenced the build including sources, dependencies, build tools, ***base images***, and so on.
> This is considered to be incomplete unless metadata.completeness.materials is true.

In tekton, this means we should record the following information in materials (feel free to suggest more if missed)
- [x] the source code repo from which artifacts are built.
- [x] step base image
- [x] sidecar base image
- [x] remote tasks referenced in a remote pipeline.yaml (this artifact can be a repo, a Tekton OCI bundle or a hub resource).

# Actual Behavior

[predicate.materials](https://slsa.dev/provenance/v0.2#materials) now only records the source code repo.

**Comment by wlynch** [comment]
SGTM!

**Comment by lcarva** [comment]
@chuangw6, that makes sense! I do think there's value in knowing which image was used in each step of each task because it allows for very targeted policies. Maybe we can add to ``predicate.materials` without changing `predicate.buildConfig` ?

**Comment by chuangw6** [comment]
> Maybe we can add to predicate.materials without changing `predicate.buildConfig` ?

That SGTM. 

I think that the idea of [the plan](https://github.com/tektoncd/chains/issues/597#issuecomment-1282918607) for the configurable formatting / aliasing  will  
- make sure `intoto` / `slsav0.1` option still keeps the current `buildConfig`.
- introduce `slsav0.2` option that will generate the provenance whose `buildConfig` is the full spec.

**Comment by chuangw6** [comment]
cc @chitrangpatel

**Comment by chuangw6** [comment]
Other than the step base images, there are few more things that should be captured in materials.
1. source of remote tasks in a remote pipeline.yaml
In the special case of a remote pipeline definition referencing remote tasks that came from other places i.e. other repos, other tekton bundles, I just realized that those remote tasks' source information should be the build materials as well while the source information of the remote pipeline definition is captured in `predicate.invocation.configSource`. 
2. sidecar base images 
Pointed out by @chitrangpatel. Similar to step base images, sidecar base images should also be captured in `predicate.materials`. 


Please comment if there is any questions. Otherwise, I'll update the issue description to reflect this later. Thanks!!

**Comment by chitrangpatel** [comment]
I think this can be closed. PRs https://github.com/tektoncd/chains/pull/658 and https://github.com/tektoncd/chains/pull/649 address this.
