### ISSUE TITLE
Default params shouldn't be in `predicate.invocation.paramaters`.

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#645]
# Expected Behavior

Default params specified in pipelineSpec / taskSpec shouldn't appear in `predicate.invocation.parameters`. 

# Actual Behavior

Default params along with params provided in PipelineRun/TaskRun are all captured in `predicate.invocation.parameters`. 

https://github.com/tektoncd/chains/blob/6d3449f5eaa65519beffef5f9cfb8c88b0dd205b/pkg/chains/formats/intotoite6/attest/attest.go#L58-L78

# Reason

Per SLSA definition for [invocation.parameters](https://slsa.dev/provenance/v0.2#invocation.parameters), 

> Collection of all external inputs that influenced the build on top of invocation.configSource.

Default params are part of the spec. As such, it shouldn't be identified as ***external inputs*** that influenced the built on the top of `invocation.configSource` which is the source of remote build definition (i.e. remote pipeline.yaml or task.yaml).

**Comment by chuangw6** [comment]
cc @lcarva

**Comment by lcarva** [comment]
From a usability perspective, having to consult two fields to determine the value of the parameter is not ideal. Anyone writing a policy to determine which parameter was used will have to merge the two sources.

If possible, I would prefer to have a single source of truth over a strict interpretation of the standard.

**Comment by chuangw6** [comment]
> If possible, I would prefer to have a single source of truth over a strict interpretation of the standard.

Sorry can you please elaborate a bit on "single source of truth"? Thanks!

**Comment by wlynch** [comment]
+1 to @lcarva 

I'm a bit hesitant about this - while technically you're right that it's not a strict requirement for SLSA, omitting the data makes it harder to see what happened in a particular build since otherwise you may need to fetch the underlying config to see what a value is.

AFAICT I don't see any downside of retaining the extra data beyond it taking up a bit more space.

**Comment by chuangw6** [comment]
Thanks for sharing your thoughts @wlynch 

My point of "Default params are part of the spec" is that if a taskrun doesn't provide a value to overwrite the param specified in taskspec that has a default value, using param references in steps is no different than using that default value directly.

That makes me think the provenance for such runs shouldn't capture that default params in spec b/c it's part of the spec itself instead of something influencing the build.

**Comment by chuangw6** [comment]
To put it a bit differently, my thought is that `predicate.invocation.parameters` would only capture the params provided in taskrun/pipelinerun spec i.e. the function will become

```go
 func Invocation(source *v1beta1.ConfigSource, params []v1beta1.Param) slsa.ProvenanceInvocation { 
 	i := slsa.ProvenanceInvocation{ 
 		ConfigSource: convertConfigSource(source), 
 	} 
 	iParams := make(map[string]v1beta1.ArrayOrString) 
  
 	// get explicit parameters 
 	for _, p := range params { 
 		iParams[p.Name] = p.Value 
 	} 
  
 	i.Parameters = iParams 
 	return i 
 } 

```

**Comment by chitrangpatel** [comment]
According to TEP https://github.com/tektoncd/community/pull/894, this will be the case. `invocation.Parameters` will have all the taskRun inputs (except `taskRef/taskSpec`) while `buildConfig` will contain the underlying `taskSpec` that was run.

So `invocation.Parameters` will contain more than just `Tekton TaskRun/PipelineRun parameters`.
