### ISSUE TITLE
Cleanup use of `sleep` in tests

### ISSUE THREAD

**Issue by bendory** [tektoncd/chains#664]
### Feature request

The use of `time.Seep` in tests is unreliable. Using it with the hope that something will happen in a given timeframe is generally a code smell for non-deterministic behavior and flaky test cases.

Instead, use a deterministic alternative to synchronize the test so that it waits until it should continue. If you can't use a proper Go channel to synchronize the behavior, consider polling for event success with a timeout.

Ref: https://testing.googleblog.com/2008/08/tott-sleeping-synchronization.html

I found [this OSS package](https://github.com/rShetty/asyncwait) with a simple example case.

### Use case

`grep sleep *_test.go` for all the places where we should cleanup our code.

**Comment by wlynch** [comment]
IIUC most of these are to allow for [volume propagation of secrets / config maps](https://ahmet.im/blog/kubernetes-secret-volumes-delay/), which is not something you can query for with the k8s API. I think if you want to drop the sleep you'd have to bounce the running pod and wait for a new pod to be ready.

**Comment by bendory** [comment]
@wlynch Some ideas:

- Could we set [configMapAndSecretChangeDetectionStrategy](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#:~:text=container.%20Default%3A%205-,configMapAndSecretChangeDetectionStrategy,-ResourceChangeDetectionStrategy) to `get` for testing purposes such that no propagation is needed? IIUC, `get` means they are looked up every time, which means that updates go live immediately (at the expense of a query on every lookup)
- Could we set [`syncFrequency`](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) to a small interval (default is `1m`) for test purposes to force the sync to happen faster?

**Comment by wlynch** [comment]
> - Could we set [configMapAndSecretChangeDetectionStrategy](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#:~:text=container.%20Default%3A%205-,configMapAndSecretChangeDetectionStrategy,-ResourceChangeDetectionStrategy) to get for testing purposes such that no propagation is needed? IIUC, get means they are looked up every time, which means that updates go live immediately (at the expense of a query on every lookup)

I don't think that will work - https://ahmet.im/blog/kubernetes-secret-volumes-delay/ has more details as to why (tl;dr it only configures how the kubelet gets the content, not how it updates the volume).

> Could we set [syncFrequency](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) to a small interval (default is 1m) for test purposes to force the sync to happen faster?

In general I don't know if we want to impose kubelet settings onto the org-shared e2e cluster pool. This would also mean we need to require this configuration on all development clusters which I suspect would be high friction for most people.

Deleting the running pod and waiting on the ready condition for the deployment to create a fresh pod seems like the most reliable and widely-compatible way if you want to remove the sleeps - I don't think this would take longer than the 30-60s sleeps we're already doing.

**Comment by chitrangpatel** [comment]
https://github.com/tektoncd/chains/pull/911 solves this issue.
We restart the chains controller pod forcing the update of secrets and ConfigMap to it. The restart takes on order a few seconds, way faster than sleeping for a minute each for secrets and configmaps to propagate down to the pods. As a result, our e2e tests are also significantly faster. 53mins --> 23 mins.
