### ISSUE TITLE
Source does not get captured when using structured results

### ISSUE THREAD

**Issue by jagathprakash** [tektoncd/chains#675]
# Expected Behavior
SLSA field materials should have the URI and commit hash of the source.

# Actual Behavior
Source not present in materials.

Note that this happens only when the source is conveyed to Chains through the StructuredResults with result name as *-ARTIFACT_INPUTS. It gets captured if the source is sent in as CHAINS-GIT_COMMIT and CHAINS-GIT_URI.

# Steps to Reproduce the Problem

1. Copy the pipeline.yaml and pipeline_run.yaml below to the respective files
2. Run pipelinerun.yaml with Chains enabled.

# Additional Info

- Kubernetes version: 

  **Output of `kubectl version`:**
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.24.7-gke.900

  ```
The material field looks like this
    "materials": [
      {
        "uri": "git+.git",
        "digest": {
          "sha1": ""
        }
      }
    ]
  ```

- Tekton Pipeline and Chain version: built from head of Repo.

The issue is the checkDigest in pkg/artifacts/signable.go supports only sha256 and not sha1.

pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: slsa-demo-pipeline
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
  results:
    - name: image-ARTIFACT_INPUTS
      description: Source code used to build the artifact.
      value:
        uri: $(tasks.fetch-source.results.url)
        digest: sha1:$(tasks.fetch-source.results.commit)
    - name: image-ARTIFACT_OUTPUTS
      description: The artifact that has been built.
      value:
        uri: $(tasks.build.results.IMAGE_URL)
        digest: $(tasks.build.results.IMAGE_DIGEST)
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-source
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: pathInRepo
            value: /task/git-clone/0.6/git-clone.yaml
          - name: revision
            value: main
      workspaces:
        - name: output
          workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
    - name: build
      runAfter: ["fetch-source"]
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: pathInRepo
            value: /task/kaniko/0.6/kaniko.yaml
          - name: revision
            value: main
      workspaces:
      - name: source
        workspace: shared-data
      params:
      - name: IMAGE
        value: $(params.image-reference)

pipeline_run.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: demo-pipelinerun-
spec:
  serviceAccountName: jp-ksa
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/jagathprakash/tekton_slsa_demo.git
      - name: pathInRepo
        value: pipeline.yaml
      - name: revision
        value: main
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Mi
  params:
  - name: repo-url
    value: https://github.com/bendory/mini-true.git
  - name: image-reference
    value: us-docker.pkg.dev/${PROJECT_ID}/${CLOUD_REPO}/${CLUSTER_NAME}

**Comment by jagathprakash** [comment]
The issue is with ARTIFACT_INPUTS
- The PipelineRun results are as shown below
   ```
      Results:
    Name:  image-ARTIFACT_INPUTS
    Value:
      Digest:  sha1:93c56eeba9ec70f74c9bfd297d9516642d366cb5
      Uri:     https://github.com/bendory/mini-true.git
    Name:      image-ARTIFACT_OUTPUTS
    Value:
      Digest:  sha256:d63ce4fef1a7cf83b6ef20d77be1fca26a7bb4a22edb5b075b07e9c0598dc05c
      Uri:     us-docker.pkg.dev/jagathprakash-test/jp-repo/slsa-demo-cluster
  ```
- For tests, the unit test TestExtractStructuredTargetFromResults tests for a valid digest but assumes that GIT_COMMIT is sha256 but git_commit is sha1. As the test value is a valid sha256 the test passes.

**Comment by bobcatfish** [comment]
Just realized that it looks like @chuangw6 may have reported this in December in https://github.com/tektoncd/chains/issues/636

**Comment by wlynch** [comment]
Duplicate of #636
