### ISSUE TITLE
Flaky E2E Tests v1.23.x

### ISSUE THREAD

**Issue by EmmaMunley** [tektoncd/chains#697]
I ran into an issue recently when submitting [this PR](https://github.com/tektoncd/chains/pull/693) where a specific E2E test failed for only the v1.23.x version after changing a variable declaration.

The only way to re-trigger the test was to re-submit a PR so I fixed a typo in the README and the test passed.

Logs:
https://github.com/tektoncd/chains/actions/runs/4045026736/jobs/6955935954

**Comment by chitrangpatel** [comment]
Is there a way to allow developers to re-run the test on GH actions dashboard? Having to push a commit is annoying since it all the tests will rerun again and if there is an `lgtm` label, it disappears due to detecting changes.
