### ISSUE TITLE
Manually bump tektoncd/pipelines dependency to v0.45

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/chains#711]
Tektoncd/Pipelines [v0.45](https://github.com/tektoncd/pipeline/releases/tag/v0.45.0) introduced some breaking changes 

eg. Removal of TaskRuns and Runs and only leaving ChildReferences are causing unit tests to fail. 
```
chitrang-macbookpro:chains chitrang$ go test ./...
# github.com/tektoncd/chains/pkg/chains/signing/x509.test
ld: warning: -no_pie is deprecated when targeting new OS versions
ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later
# github.com/tektoncd/chains/pkg/reconciler/pipelinerun
pkg/reconciler/pipelinerun/pipelinerun.go:75:58: pr.Status.TaskRuns undefined (type "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1".PipelineRunStatus has no field or method TaskRuns)
pkg/reconciler/pipelinerun/pipelinerun.go:75:89: pr.Status.Runs undefined (type "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1".PipelineRunStatus has no field or method Runs)
pkg/reconciler/pipelinerun/pipelinerun.go:76:39: pr.Status.TaskRuns undefined (type "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1".PipelineRunStatus has no field or method TaskRuns)
```

The source code in Chains needs to be updated to work with this change.

**Comment by chitrangpatel** [comment]
Good catch. I need to validate that. I will do that and report here again.

**Comment by chuangw6** [comment]
seems like https://github.com/tektoncd/chains/pull/712 has solved this. Is there anything left to do for this issue?

**Comment by wlynch** [comment]
That solved the initial breakage, but we want to add back support so we don't break compatibility with older LTS sever versions.

**Comment by lcarva** [comment]
I think we can close this now with https://github.com/tektoncd/chains/pull/787
