### ISSUE TITLE
Documentation update - Tekton chains using Vault

### ISSUE THREAD

**Issue by cooktheryan** [tektoncd/chains#713]
### Feature request

I'm having an issue trying to figure out all of the correct settings to be able to sign images using a key stored in vault.  I don't believe I am the only one based on some of the comments in #609 

### Use case

A documentation update would allow for greater adoption of this feature

**Comment by wlynch** [comment]
Using [`hashivault://`](https://docs.sigstore.dev/cosign/kms_support#hashicorp-vault) with `signers.kms.kmsref` will probably be easier to work with (and doesn't require privileged CSI driver).

I'll try and whip together a quick getting started guide next week!
