### ISSUE TITLE
Add support for signing keyless with Security Token Service (STS) identity

### ISSUE THREAD

**Issue by sallyom** [tektoncd/chains#717]
### Feature request

Document and add necessary options for the chains config to pick up a Security Token Service (STS) identity token. These are similar to the already present KMS options.
I believe this will be the same for AWS & GCP STS but have only used AWS currently.

### Use case

I'd like to be able to use keyless flow with workload identity issued by STS.

**Comment by sallyom** [comment]
I'd like to contribute the work to resolve this issue.

**Comment by wlynch** [comment]
More documentation always welcome! :D 

https://github.com/tektoncd/chains/blob/main/docs/sigstore.md#keyless-signing-mode and https://github.com/tektoncd/chains/blob/main/docs/config.md#keyless-signing-with-fulcio are good places to start. Chains is using cosign under the hood, so many of the same options / environment variables will carry over. 

Where you find gaps, let us know!

**Comment by sallyom** [comment]
Will do, thanks!
