### ISSUE TITLE
Support SLSA 1.0 provenance spec

### ISSUE THREAD

**Issue by mlieberman85** [tektoncd/chains#728]
### Feature request

SLSA 1.0 requirements and the provenance spec are now in draft. It will be be going fully 1.0 approximately end of March 2023. See: https://slsa.dev/provenance/v1-rc1

### Use case

SLSA is becoming a major framework for provenance in supply chain security. With 1.0 being released in draft and there being maybe a few minor changes for the full 1.0 release users of SLSA are going to start looking to switch to the full 1.0 release.

**Comment by wlynch** [comment]
@chitrangpatel we might want to look into pivoting [v2alpha1](https://github.com/tektoncd/chains/tree/main/pkg/chains/formats/slsa/v2) to using SLSA v1 👀

**Comment by mlieberman85** [comment]
Also, there is supporting the SLSA 1.0 requirements, which I think Tekton + Chains should already do, but there might just need to be something like a document describing how.l

**Comment by chitrangpatel** [comment]
go go go...
/assign

**Comment by chitrangpatel** [comment]
Update: Implementation is completed (https://github.com/tektoncd/chains/issues/797).
BuildType and usage documentation is required.
