### ISSUE TITLE
Remove PipelineResource support

### ISSUE THREAD

**Issue by wlynch** [tektoncd/chains#734]
PipelineResources have been deprecated from Pipelines for quite some time now (https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md#deprecation-table says since Dec 2021) - we should be safe to rip this out from Chains.

**Comment by wlynch** [comment]
Heads up - Pipelines was still allowing creation of PipelineResources via v1beta1 through v0.45.0, so it's very likely that there's still usage of Pipeline Resources for recent clients.

[Support was removed in v0.46.0](https://github.com/tektoncd/pipeline/pull/6150), but the API types were removed as well so this breaks our ability to safely watch older Tekton versions if we update our client version to v0.46.0 😭

I reached out on the Pipelines PR to ask to roll back the client changes.

**Comment by chuangw6** [comment]
After creating https://github.com/tektoncd/chains/pull/764 to remove it, I just realized this ticket. Thanks for creating this ticket. 

Should we remove support for the pipelineresources in Chains? I feel like if we don't remove it, users who uses the combo of pipeline >= v0.46 and chains >= 0.16 will have trouble.

**Comment by lcarva** [comment]
> Should we remove support for the pipelineresources in Chains? I feel like if we don't remove it, users who use the combo of pipeline >= v0.46 and chains >= 0.16 will have trouble.

Good question. According to [this](https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md#removed-features), the pipeline release v0.44.0 is still supported until Jan 24, 2024. So maybe we should until then?

**Comment by wlynch** [comment]
I'd like to keep compatibility with current supported pipeline LTS versions, unless there's a good reason we can't.

We got the resources API change reverted in https://github.com/tektoncd/pipeline/pull/6436 - if/when pipeline releases v0.46.1 we should be able to upgrade with compatibility.
