### ISSUE TITLE
e2e tests: Error: unknown shorthand flag: 'n' in -n

### ISSUE THREAD

**Issue by wlynch** [tektoncd/chains#747]
e2e tests are failing to output debug data. Looks like `kind` is returning "" in:

https://github.com/tektoncd/chains/blob/46f16e28b6e2268eb8d7fdbb4f678b67300f4dd5/test/test_utils.go#L213

```
test_utils.go:212: ============================== tekton.dev/v1beta1/PipelineRun logs ==============================
test_utils.go:214: Error: unknown shorthand flag: 'n' in -n
```

https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_chains/739/pull-tekton-chains-integration-tests/1638988991220944896

Sample CLI run that produces the same error:

```
$ tkn logs -n asdf
Error: unknown shorthand flag: 'n' in -n
```

We should figure out why this data isn't being plumbed through.

**Comment by lcarva** [comment]
You'd get the same error if `kind` is not an empty string but an unexpected type:
```
🐚 tkn blah logs -n asdf
Error: unknown shorthand flag: 'n' in -n
```
