### ISSUE TITLE
Remove TaskRunResults from `slsa/v2alpha1`

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/chains#750]
PR https://github.com/tektoncd/chains/pull/663 added `taskRunResults` to the `buildConfig`.

However, the buildConfig should only be static information from the build configuration, not the runtime info too and taskRunResults is definitely runtime information. 
Having said that, I'm not sure where we would fit the `taskRunResults` in this case because there is no obvious place in the `SLSAv0.2 predicate`.

We could reach out to the SLSA folks and ask for guidance on this. But as is, I don't think `taskRunResults` belongs in the `buildConfig` should probably be removed.

Thoughts???

**Comment by chitrangpatel** [comment]
cc @bobcatfish @chuangw6 @wlynch @lcarva

**Comment by lcarva** [comment]
Runtime information, like TaskRun results, is super valuable when writing advanced policies. The new SLSA spec will have a place for this under byproducts, see [#649](https://www.github.com/slsa-framework/slsa/issues/649). But I think that may not be sufficient. For instance, tracking the order the TaskRuns were executed might be challenging.

We may want to introduce a new predicate that includes pretty much the TaskRun/PipelineRun resource.

That way, Chains can generate a very clean SLSA Provenance attestation which makes most users happy. But also a Chains specific attestation for those of us who need additional information in their policies.

**Comment by wlynch** [comment]
+1 to what @lcarva said. There's still value in storing the result values, though I'm fine if we move them out of `buildConfig` to somewhere else (byproducts, etc).

I like the idea of attaching the full spec as it's own separate attestation that's linked to from the main SLSA attestation. This is also a nice pattern to let us eventually attach additional attestations like Pod spec as well.

**Comment by wlynch** [comment]
Since SLSA v1 sounds like it is imminent (last I heard ETA for final v1 spec was mid-late April), one option is we freeze support for SLSA v0.2 in our v1 spec, and focus on SLSA v1 for v2. This would sidestep the issue for v0.2.

If we have a reason to keep developing against SLSA v0.2 - we could find another home like extending `invocation` with our own fields that we need. I see enough value for these fields that I wouldn't want to just drop them without a replacement.
