### ISSUE TITLE
Mark `metadata.completeness.parameters` as `True` for `slsa/v2alpha1` task run level provenance

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/chains#751]
### Feature request

Mark `metadata.completeness.materials` and `metadata.completeness.parameters` as `True` for `slsa/v2alpha1` task run level provenance.
 
### Reason

[TEP 0122 - Complete Build Instructions](https://github.com/tektoncd/community/blob/main/teps/0122-complete-build-instructions-and-parameters.md) identified all missing run-time parameters and materials. I think we have captured all the run time parameters and materials and implemented them for `slsa/v2alpha1`.

I don't think `metadata.completeness.environment` is complete yet since its likely missing some more information (currently it only contains the feature flags that the pipelines controller was configured with).

**Comment by chitrangpatel** [comment]
cc @bobcatfish

**Comment by wlynch** [comment]
parameters sgtm, materials I don't think we can guarantee until pipeline controls like hermekton land.

> metadata.completeness.materials boolean, optional
> 
> If true, the builder claims that materials is complete, usually through some controls to prevent network access. Sometimes called “hermetic”.

**Comment by chitrangpatel** [comment]
Updating the title to reflect the change that we are only going to mark `parameters` as complete, not materials.

**Comment by chitrangpatel** [comment]
Marking this as closed.
