### ISSUE TITLE
Call for a doc on how to use Pipelines with Chains

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#786]
One important step before using Chains is to write a Tekton Pipeline/Task and make sure the source artifacts being used and output artifacts being generated can be captured by Tekton Chains.

In Chains, currently there is no dedicated doc telling users how to write appropriate Tekton Pipeline/Task yamls. Type hinting sections attempt to do that but it's spreading across the 2 docs [config.md](https://github.com/tektoncd/chains/blob/main/docs/config.md) and [intoto.md](https://github.com/tektoncd/chains/blob/main/docs/intoto.md). 

So it would be great to have a dedicated doc telling users how to use Pipeline with Chains.

Proposal:

- remove "Chains type hinting" section from [config.md](https://github.com/tektoncd/chains/blob/main/docs/config.md) and make sure [config.md](https://github.com/tektoncd/chains/blob/main/docs/config.md) only focus on how to configure Chains (not pipelines). 
- split [intoto.md](https://github.com/tektoncd/chains/blob/main/docs/intoto.md) into 2 docs: 
  - `intoto.md` itself: This doc should focus on SLSA provenance itself i.e. slsa brand, formatting etc. I am open for ideas. 
  - `using_with_Tekton_Pipelines.md`: This doc should focus on how to use Tekton Pipelines with Tekton Chains.

**Comment by lcarva** [comment]
+1 for this. I think pointing to examples in the [catalog](https://github.com/tektoncd/catalog/) is probably a good idea too.

**Comment by AlanGreene** [comment]
also fyi: https://github.com/tektoncd/website/pull/530
PR for new doc on the website showing how to use chains
