### ISSUE TITLE
migration from `PodSecurityPolicy` to `PodSecurityAdmission`?

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#794]
Tekton Pipeline has migrated from `PodSecurityPolicy` to `PodSecurityAdmission` in https://github.com/tektoncd/pipeline/pull/5652. And currently there is [PSA set up](https://github.com/tektoncd/pipeline/blob/2ae8b6a54a1bab401dbd3b1cc533a3b087ca54ea/config/100-namespace/100-namespace.yaml#L22) in the `tekton-pipelines` namespace.

But currently in `tekton-chains` namespace there is [no PSA currently set up](https://github.com/tektoncd/chains/blob/82c213c172a99329d6571d76499ad816755a9069/config/100-deployment.yaml#L15-L21).

**Comment by wlynch** [comment]
SGTM!
