### ISSUE TITLE
Cleanup Materials usage

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/chains#816]
Some of the functions in material take a pointer address to a materials slice. This is not a good practice for two reasons:

1. It seems bad practice to pass a slice pointer around.
2. Other functions on the `materials` package deal with adding things to materials but don't take a pre-existing slice, e.g. `AddMaterialsFromTaskParamsAndResults`.

We should be consistent with how we extract materials. Something like this could work:

```go
allMaterials := []common.ProvenanceMaterial{}

mats, err := material.FromStepImages(tro.Status.Steps)
if err != nil {...}
allMaterials = append(allMaterials, mats...)
```

We need to clean up the usage of materials and make it consistent.

**Comment by chitrangpatel** [comment]
cc @chuangw6

**Comment by chuangw6** [comment]
Thanks @chitrangpatel! I think we would need to finish this cleanup before cutting next release.

**Comment by chitrangpatel** [comment]
Closing this following merged PR https://github.com/tektoncd/chains/pull/857
