### ISSUE TITLE
Tekton-specialized buildType for SLSAv1.0 predicate

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/chains#864]
### Feature request

The current `v2alpha2` predicate type in Chains is based on the [following design](https://docs.google.com/document/d/1ewqtPXyg_y3MmU6Tc6l1X8nfzjt0AJHlP6VOnFsGNpQ/edit#heading=h.8hw7rf805u8r). It follows the principles laid out by [slsa.dev](https://slsa.dev/) and generates provenance that can be consumed by generic verifiers.

However, there have been a couple of requests to have a more specialized version of the provenance so that more in-depth verification of the Tekton object can be conducted.
- https://github.com/tektoncd/chains/issues/824
- https://github.com/tektoncd/chains/issues/839
- https://github.com/tektoncd/chains/issues/834

Therefore, in the [Tekton Chains WG meeting](https://docs.google.com/document/d/1UVPSCDyNO-TzEFSv8jrqrEOF_FmV8NFuXncFm1gwmeY/edit#heading=h.3rqi4wuek4ye), we decided that the best approach might be to produce a new **BuildType** that contains a much more `verbose` SLSA 1.0 provenance tuned for `Tekton specialized` verifiers. 

### Use case
- Tekton specialized verifiers can use this buildType for validating internal details of the provenance.

**Comment by chitrangpatel** [comment]
cc @wlynch @lcarva @joejstuart @chuangw6

**Comment by chitrangpatel** [comment]
Due to my bandwidth restrictions, someone else may have to do the heavy-lifting here. Happy to help with reviews etc.

**Comment by joejstuart** [comment]
@chitrangpatel I should be able to pick this up if someone is still in need. To start, I was thinking submitting a design doc to outline the requirements for this new build definition.

**Comment by chitrangpatel** [comment]
That would be amazing @joejstuart ! 
A design doc for the new build definition sounds like a great start !

**Comment by joejstuart** [comment]
Here's [a design](https://docs.google.com/document/d/1ddt9oKXUrhRdHmibsgmaznNlpoEbVgOvjuL6EeRwaqY/edit?resourcekey=0--sS7uiVoXJQqvv5cbIKkcw) based off of the [original document](https://docs.google.com/document/d/1ewqtPXyg_y3MmU6Tc6l1X8nfzjt0AJHlP6VOnFsGNpQ/edit#heading=h.8hw7rf805u8r). PTAL! 
Just a couple of questions I have is should this buildType be gated by the config? Will all buildTypes be generated on each build or should there only be one buildType generated on each build?

**Comment by chitrangpatel** [comment]
> Here's [a design](https://docs.google.com/document/d/1ddt9oKXUrhRdHmibsgmaznNlpoEbVgOvjuL6EeRwaqY/edit?resourcekey=0--sS7uiVoXJQqvv5cbIKkcw) based off of the [original document](https://docs.google.com/document/d/1ewqtPXyg_y3MmU6Tc6l1X8nfzjt0AJHlP6VOnFsGNpQ/edit#heading=h.8hw7rf805u8r). PTAL!

Thanks! I left some small comments in there. Overall, lgtm!

> Just a couple of questions I have is should this buildType be gated by the config? Will all buildTypes be generated on each build or should there only be one buildType generated on each build?

Yes, I think the build types should be gated by config. We should not generate all buildTypes for the provenance. Based on the config, we should generated the desired buildType.

**Comment by chitrangpatel** [comment]
This has been fixed.
