### ISSUE TITLE
Hardened Tekton!

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/chains#87]
I'm imagining a Tekton Cat but with the chains necklace on, hanging out with the Falco logo. The cat will be holding some kind of shield with the SPIFFE logo on it, and we can throw in some sigstore/cosign logos too when we get them.

Ref https://github.com/cncf/tag-security/issues/625#issuecomment-841510718

But anyway - the real is to try to put together an end to end hardened build system using Falco policies to detect runtime issues. Use something like SPIRE to tie builds to specific machines, and some kind of TPM attestations for integrity of the build system itself and the individual build instances.

In-toto, sigstore and hermekton can provide a secure end to end provenance of build artifacts, which could include these build system and build node attestations all the way back to a hardware root of trust.

**Comment by lukehinds** [comment]
I would certainly be interested in looking at the TPM part (I just need to get my head around the mapping from an abstracted container layer to the hosts hardware and how we retain the hardware root of trust all the way up).

Tagging @lkatalin

**Comment by dlorenc** [comment]
This would have to go through a TEP, but one other idea to attest build node identity (through say, SPIRE) would be for the Tekton pipelines controller to inject some kind of challenge token as an env variable into each TaskRun.

The entry pointer could generate a keypair and get an x509 SVID from SPIRE. The key would sign the challenge token, generating a response.

The response and SVID bundle could be output as a result of the run, and verified by the controller. The controller challenge could be a random nonce kept in memory, or (for HA) a fixed secret HMACed against the TaskRun selflink/uuid.

Chains could then verify all of this - the orchestrator workload identity AND the build workload identity, and include this in the final signed provenance.

Ref https://github.com/in-toto/attestation/issues/36

**Comment by dlorenc** [comment]
> I would certainly be interested in looking at the TPM part (I just need to get my head around the mapping from an abstracted container layer to the hosts hardware and how we retain the hardware root of trust all the way up).

My very loose understanding here is that most k8s workloads go through the SPIRE API for things like this. The SPIRE API can be configured to do TPM roots of trust and issue SVIDs to actual running workloads in the cluster. Here's one example: https://github.com/bloomberg/spire-tpm-plugin

**Comment by colek42** [comment]
@dlorenc https://github.com/boxboat/spire-tpm-plugin is our fork of that plugin -- we do plan to upstream it.

**Comment by dlorenc** [comment]
Nice!!!

**Comment by dlorenc** [comment]
One other possibility:

- Tekton (and chains) now relies on pod statuses to parse outputs, but these statuses can be written by anyone with edit permissions on the pod
- This means we don't **know** the results came from the actual pod.

Projected volume service accounts can help here: https://cloud.google.com/community/tutorials/gke-workload-id-clientserver

- Each taskrun could generate an ephemeral private key and sign all the results before writing to disk.
- The corresponding public key could be "registered" to the taskrun via an API call (to chains? fulcio? something else?) using the projected auth token. The entrypointer could do this before dropping networking for hermekton.
- This key can be used to sign all the results before they're picked up by Tekton
- Chains can verify all the signatures against the public key before creating a signed provenance payload
