### ISSUE TITLE
uuid in annotation 

### ISSUE THREAD

**Issue by lukehinds** [tektoncd/chains#96]
We add a UUID to annotations for payload-taskrun and signature-taskrun

```json
"annotations": {
      "chains.tekton.dev/payload-taskrun-8c0e9bbc-192b-4ea3-8a6d-26d2ac1e0024": "eyJjb25kaXRpb25zIjpbeyJ0eXBlIjoiU3VjY2VlZGVkIiwic3RhdHVzIjoiVHJ1ZSIsImxhc3RUcmFuc2l0aW9uVGltZSI6IjIwMjEtMDUtMjFUMDk6NDI6MTFaIiwicmVhc29uIjoiU3VjY2VlZGVkIiwibWVzc2FnZSI6IkFsbCBTdGVwcyBoYXZlIGNvbXBsZXRlZCBleGVjdXRpbmcifV0sInBvZE5hbWUiOiJzYW1wbGUtcGlwZWxpbmUtcnVuLWVjaG8tc29tZXRoaW5nLWJqOHI3LXBvZC1zd3J3cyIsInN0YXJ0VGltZSI6IjIwMjEtMDUtMjFUMDk6NDI6MDRaIiwiY29tcGxldGlvblRpbWUiOiIyMDIxLTA1LTIxVDA5OjQyOjExWiIsInN0ZXBzIjpbeyJ0ZXJtaW5hdGVkIjp7ImV4aXRDb2RlIjowLCJyZWFzb24iOiJDb21wbGV0ZWQiLCJzdGFydGVkQXQiOiIyMDIxLTA1LTIxVDA5OjQyOjEwWiIsImZpbmlzaGVkQXQiOiIyMDIxLTA1LTIxVDA5OjQyOjEwWiIsImNvbnRhaW5lcklEIjoiY29udGFpbmVyZDovL2JkNzBkNDBkMGU4NThkNjc0ZDM3ZjIyMDg3NGIzODI3NzExZmE3YzEyYzBmM2I0Yjk0YTE4YTkwNDQxZTc2NjYifSwibmFtZSI6ImVjaG8iLCJjb250YWluZXIiOiJzdGVwLWVjaG8iLCJpbWFnZUlEIjoicmVnaXN0cnkuYWNjZXNzLnJlZGhhdC5jb20vdWJpOC1taW5pbWFsQHNoYTI1NjpmYzc1NTMyYTIwYzFlN2ViMDUxMmEwM2ZlYWM0NjU1NDI3OGJjZTk0NmNmNDU0YTc4ZTExNDMzZTM5YTY2ZDJkIn1dLCJ0YXNrU3BlYyI6eyJzdGVwcyI6W3sibmFtZSI6ImVjaG8iLCJpbWFnZSI6InJlZ2lzdHJ5LmFjY2Vzcy5yZWRoYXQuY29tL3ViaTgtbWluaW1hbCIsImNvbW1hbmQiOlsiZWNobyJdLCJhcmdzIjpbImhlbGxvIHdvcmxkIl0sInJlc291cmNlcyI6e319XX19",
      "chains.tekton.dev/signature-taskrun-8c0e9bbc-192b-4ea3-8a6d-26d2ac1e0024": "MEQCIHOOgvkybfaea7moBVHfhyH+BZTBVtdDkxrqiBghWkWFAiBOLuNtvR6nML7TsgddcfKRB+fnbpBpjcr+NLn/vGrFrA==",
      "chains.tekton.dev/signed": "true",
      "pipeline.tekton.dev/release": "devel"
    },

```

I guess there is a reason for this? I ask as it might it more cumbersome for folks to parse out the values as they will need to find the UUID or use some sort of regex or wildcard to ignore the appended uuid.

**Comment by priyawadhwa** [comment]
Looks like it was added in https://github.com/tektoncd/chains/pull/66! @dlorenc might know more about how necessary it is to include the UID in the annotation

**Comment by dlorenc** [comment]
It was more laziness and lack of creativity on the proper interfaces.

Objects (Taskruns and OCI artifacts right now) get signed and stored somewhere
The signatures can get stored in the Taskrun yaml itself OR a document database, etc.
The signatures need a unique key to identify them in the storage namespace.
When signatures for a taskrun get stored **in the same taskrun** - they don't need a unique name because it's already unique.

I couldn't figure out how to special case that cleanly.

**Comment by lukehinds** [comment]
Is it any particular storage system that needs this? Putting my database head on, there would normally be a primary key that is the unique element and requiring key constraints. 

Another option would be to use the taskrun name:

```
tkn taskrun list
NAME                                       STARTED          DURATION    STATUS
pipeline-example-bj8r7   11 seconds ago   7 seconds   Succeeded
```

```
"annotations": {
      "chains.tekton.dev/payload-taskrun-pipeline-example-bj8r7": "payload",
      "chains.tekton.dev/signature-taskrun-pipeline-example-bj8r7": "sig",
      "chains.tekton.dev/signed": "true",
      "pipeline.tekton.dev/release": "devel"
    },
```

This way people have a look up value they can know the key in advance to perform a look up.

**Comment by priyawadhwa** [comment]
+1 to using the taskrun name, it would probably be easier for users

**Comment by dlorenc** [comment]
The taskrun name isn't necessarily unique, you can delete one and create it again, that's kind of the issue there.

**Comment by lukehinds** [comment]
understood, this is not a high prio so we can try to figure this out later. From what I can see most users will try to regex / wildcard around this, as I don't believe they can query for the UUID and then construct a value by concat'ing the taskrun name + uuid to retrieve the entry, it looks like we are adding this uuid just so its able to be stored in docdb (I might have all this wrong, so pls do correct me if so).
