### ISSUE TITLE
Documentation is not clear on what requirements must be met for chains to perform automatic OCI signing.

### ISSUE THREAD

**Issue by dlydiard** [tektoncd/chains#991]
Using Kaniko for a combined build and push step, Tekton Chains successfully signs and attests the OCI image in the repository. However, when splitting these steps between Kaniko for building and Crane for pushing, Tekton Chains does not perform the signing or attestation.

While a pull-secret linked to the pipeline's ServiceAccount works without issue for private ECR repositories with Kaniko, Tekton Chains does not sign images when using other OCI builders like Buildah. The exact conditions needed to trigger Tekton Chains' automatic signing are currently unclear to me.

**Comment by lcarva** [comment]
@dlydiard, have you had a chance to look at the [type hinting docs](https://github.com/tektoncd/chains/blob/main/docs/slsa-provenance.md#type-hinting)?

Chains has no insight into what tool was used to build the image. It relies on Task/Pipeline results following a certain naming convention.

Can you share the Tasks you used?

**Comment by dlydiard** [comment]
i wasn't aware of type hinting. At a glance this looks like it will solve my use case of splitting the build/push process. My result output did not include both `IMAGE_DIGEST` and `IMAGE_URL` in the Crane push Task. I will give this a try, thanks!
